### ISSUE TITLE
Namecolor

### ISSUE THREAD

**Issue by Kyphers** [AdvancedPlugins/Chat#1]
### Describe the feature

basically similar to chatcholor but a way to apply graidents and colors to a players name with gui selection and a placeholder to return the values.

**Comment by MakeItReaal** [comment]
+1

**Comment by Sp00kableDev** [comment]
+1

**Comment by ThomasWega** [comment]
Hey! Great suggestion! We have moved suggestions to discord, where community votes on features to be added. Not a lot of people use github. If you are still interested in us adding this feature, please add it in the discord server. Thank you! <3

**Comment by MakeItReaal** [comment]
Dear @ThomasWega 

I'm not able to make the request on discord since I dind't buy the plugin yet since i wanted to wait for a few suggestions.
My name on discord is NxTPanic
