### ISSUE TITLE
Problem with Cyrillic characters in chat

### ISSUE THREAD

**Issue by ququshkaaeng** [AdvancedPlugins/Chat#100]
### Describe the bug

When writing any letters in Cyrillic, it shows this.

### How to reproduce

Start a server
Write any letter in Cyrillic

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/168487334/56757a5c-3871-4592-bce7-482ddefac62f)
![image](https://github.com/AdvancedPlugins/Chat/assets/168487334/faeed436-a686-413a-9bd2-e669a776dc21)

### Server Log

https://mcpaste.io/9d5b506ce3997ff0

**Comment by EixaT** [comment]
https://pastebin.com/T8C5M9S8

**Comment by ThomasWega** [comment]
Can you send me some of the characters you are trying to use?

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Sorry for the inconvinience
