### ISSUE TITLE
Problem with command [item]

### ISSUE THREAD

**Issue by EixaT** [AdvancedPlugins/Chat#101]
### Describe the bug

When I use [item] with an object, it is not shared, it only sends text <nick> -> [item].

You can talk to the Moderator | Vision not_vision, he answered me.

### How to reproduce

![image](https://github.com/AdvancedPlugins/Chat/assets/131282124/2ef9243e-23c9-40e2-97de-7ae8019b7806)

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/131282124/2ef9243e-23c9-40e2-97de-7ae8019b7806)

**Comment by ThomasWega** [comment]
Are you on latest plugin ver? What's the server version?

**Comment by EixaT** [comment]
yes all latest,

**Comment by ThomasWega** [comment]
Will handle it here https://github.com/AdvancedPlugins/Chat/issues/120
