### ISSUE TITLE
/msg papi error and /r don't work

### ISSUE THREAD

**Issue by MrJuju0319** [AdvancedPlugins/Chat#102]
### Describe the bug

Hey send message but look screen 
![222](https://github.com/AdvancedPlugins/Chat/assets/16257583/25986de1-8c1a-4e77-a32f-046fa982eb67)
![111](https://github.com/AdvancedPlugins/Chat/assets/16257583/ffec1aba-c849-4fdf-857d-123229adf3b8)

### How to reproduce

type /msg for other et other try /r you 
/msg is You for You

### Server Log

https://mcpaste.io/2c979984a7e75661

**Comment by GC-spigot** [comment]
Hey, yeah this is papi fail. We've solved this for next update, Change in lang files `messages.msg.outgoing` text to `%recipient_name%` for message recipient , like this:
![image](https://github.com/AdvancedPlugins/Chat/assets/13188801/7dd32ed5-5ea4-4f2e-a5bb-11b3dd1b661c)

**Comment by MrJuju0319** [comment]
Bug on /r 
![image](https://github.com/AdvancedPlugins/Chat/assets/16257583/1c8ba177-c0ed-4e01-a779-668be1fcfcf0)

**Comment by MrJuju0319** [comment]
@GC-spigot
