### ISSUE TITLE
support unicode in chat 

### ISSUE THREAD

**Issue by seath15** [AdvancedPlugins/Chat#103]
### Describe the feature

add support for unicode 
![image (4)](https://github.com/AdvancedPlugins/Chat/assets/92708599/bd089feb-87d2-424d-9188-f8678b1b35de)

**Comment by wundertraume** [comment]
some

**Comment by ThomasWega** [comment]
already reported. Will work on it asap
https://github.com/AdvancedPlugins/Chat/issues/103
