### ISSUE TITLE
add support legacy colors

### ISSUE THREAD

**Issue by wundertraume** [AdvancedPlugins/Chat#105]
### Describe the bug

add support legacy colors

### How to reproduce

its all

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/118831819/560396ce-5121-48d3-8d8e-77c17c721874)

**Comment by ThomasWega** [comment]
We support legacy, but only the formats without the `x` in between. You can either use minimessage (preferred), normal legacy (&e&lTEST) or hex legacy like so &##3c2231TEST. As much as I'd like to add this x format, it would complicate a lot of stuff. It's already enough of a mess. Hopefully you can find a way to use one of these three formats
