### ISSUE TITLE
Console Spam With New Versions 1.2.3 and 1.2.4

### ISSUE THREAD

**Issue by DontMessWithDis** [AdvancedPlugins/Chat#107]
### Describe the bug

The console is continuously spammed with errors from advanced chat.

### How to reproduce

Install the newest versions on 1.20.4 or 1.21 and it will spam the console 

### Screenshots / Videos

https://paste.dedimc.io/yumovivomi

### Server Log

https://paste.dedimc.io/yumovivomi

**Comment by DontMessWithDis** [comment]
here's also my latest.log file

**Comment by GC-spigot** [comment]
Should be solved, if it comes up again in next update reply to this message.
