### ISSUE TITLE
Getting an error after editing the format section.

### ISSUE THREAD

**Issue by Flame4206** [AdvancedPlugins/Chat#109]
### Describe the bug

I was editing the format of my chat for each group and I guess I made an error somewhere. However I cannot find the error to save my life. Photo's are attached and the server error log is attached, any help would be greatly appreciated!

### How to reproduce

I guess just configure the format section incorrectly? I don't know.

### Screenshots / Videos

![Screenshot 2024-06-23 000014](https://github.com/AdvancedPlugins/Chat/assets/173592916/07af16cf-44c1-4af0-ac81-887ba919295d)
![Screenshot 2024-06-23 000025](https://github.com/AdvancedPlugins/Chat/assets/173592916/6b8e47e7-8def-4657-9373-ac336d0b3b7a)
![Screenshot 2024-06-23 000034](https://github.com/AdvancedPlugins/Chat/assets/173592916/45a755e3-9c53-4b03-92b1-f4da3b05d6b9)
![Screenshot 2024-06-23 000044](https://github.com/AdvancedPlugins/Chat/assets/173592916/036d14ad-96f8-4402-ac41-b6a42bc67920)
![Screenshot 2024-06-23 000054](https://github.com/AdvancedPlugins/Chat/assets/173592916/3c53db63-28d1-47db-8fc3-ce386dc1b7fb)
![Screenshot 2024-06-23 000103](https://github.com/AdvancedPlugins/Chat/assets/173592916/7ac6b4a7-cc85-4213-8e8b-0cf52f352fdb)
![Screenshot 2024-06-23 000117](https://github.com/AdvancedPlugins/Chat/assets/173592916/da9d42b6-a0e1-41e3-8e0f-f6091631e425)
![Screenshot 2024-06-22 235551](https://github.com/AdvancedPlugins/Chat/assets/173592916/01c16cd9-56d2-48ef-9f6f-294b04878d7f)

### Server Log

https://mcpaste.io/f739443435c8647f

**Comment by Flame4206** [comment]
When I join the server I also get this error: https://mcpaste.io/c3fbd7a5305badb8

**Comment by ThomasWega** [comment]
It seems to be more command, not formats
