### ISSUE TITLE
Essentials Compatibility

### ISSUE THREAD

**Issue by DontMessWithDis** [AdvancedPlugins/Chat#111]
### Describe the feature

I'd love to see this plugin have compatibility with Essentials commands like /msg, /reply, /ignore etc. Currently ignore, msg, and reply don't work properly with current versions. I love the plugin and hope to keep using it!

**Comment by ThomasWega** [comment]
What's the incompatibility? I've already replied on your last issue that you can change our command names and everything in commands.yml

**Comment by DontMessWithDis** [comment]
Upon a second restart the plugin disabled itself actually so its not working xD I tried renaming like you suggested, I also tried putting a # in front of the lines I don't want and also deleting them entirely. All don't work.
[latest (13).log](https://github.com/user-attachments/files/15993426/latest.13.log)

**Comment by DontMessWithDis** [comment]
# Allows to customize commands and their subcommand
# Please note that reload won't work and the server needs to be FULLY restarted in order to apply changes

advancedchat:
  command: advancedchat
  permission: advancedchat.use
  description: Main command for AdvancedChat
  aliases:
    - achat
    - chat
    - achats
    - ac
    - adc
  subcommands:
    announce:
      command: announce
      permission: advancedchat.command.announce
      description: Announce a message to all players
      aliases: [ ]
    clear:
      command: clear
      permission: advancedchat.command.clear
      description: Clear the chat
      aliases: [ ]
    info:
      command: info
      permission: advancedchat.command.info
      description: Display information
      aliases: [ ]
    preview:
      command: preview
      permission: advancedchat.command.preview
      description: Preview an auto-announcement message privately
      aliases: [ ]
    reload:
      command: reload
      permission: advancedchat.command.reload
      description: Reload the plugin
      aliases: [ ]
    commands:
      command: commands
      permission: advancedchat.command.commands
      description: List all custom commands
      aliases: [ ]
alert:
  command: alert
  permission: advancedchat.command.alert
  description: Sends an alert message to all staff members
channel:
  command: channel
  description: Change your chat channel
  aliases:
    - ch
  subcommands:
    join:
      command: join
      permission: advancedchat.command.channel.join
      description: Join a channel
      aliases: [ ]
    leave:
      command: leave
      permission: advancedchat.command.channel.leave
      description: Leave a channel
      aliases: [ ]
channels:
  command: channels
  permission: advancedchat.channels
  description: List all available channels
  aliases:
    - chs
channelspy:
  command: channelspy
  permission: advancedchat.command.channel.spy
  description: Spy on messages from a specific channel
  aliases:
    - chspy
  subcommands:
    all:
      command: all
      permission: advancedchat.command.channel.spy.all
      description: Spy on messages from all channels
      aliases: [ ]
    channel:
      command: channel
      permission: advancedchat.command.channel.spy.channel
      description: Spy on messages from a specific channel
      aliases: [ ]
    list:
      command: list
      permission: advancedchat.command.channel.spy.list
      description: List all channels you are spying on
      aliases: [ ]
channelunspy:
  command: channelunspy
  permission: advancedchat.command.channel.unspy
  description: Stop spying on messages from a specific channel
  aliases:
    - chunspy
  subcommands:
    all:
      command: all
      permission: advancedchat.command.channel.unspy.all
      description: Stop spying on messages from all channels
      aliases: [ ]
    channel:
      command: channel
      permission: advancedchat.command.channel.unspy.channel
      description: Stop spying on messages from a specific channel
      aliases: [ ]
esmmsg:
  command: esmmsg
  permission: advancedchat.command.esmmsg
  description: Send a private message to a player
  aliases:
    - esmamsg
    - esmm
    - tell
    - esmwhisper
    - esmw
    - esmt
    - esmpm
    - esmmessage
esmreply:
  command: esmreply
  permission: advancedchat.command.esmreply
  description: Reply to the last private message
  aliases:
    - esmr
spy:
  command: spy
  permission: advancedchat.command.spy
  description: Spy on private messages
  aliases:
    - msgspy
    - aspy
  subcommands:
    all:
      command: all
      permission: advancedchat.command.spy.all
      description: Spy on all private messages
      aliases: [ ]
    player:
      command: player
      permission: advancedchat.command.spy.player
      description: Spy on a specific player's private messages
      aliases: [ ]
    list:
      command: list
      permission: advancedchat.command.spy.list
      description: List all players you are spying on
      aliases: [ ]
unspy:
  command: unspy
  permission: advancedchat.command.unspy
  description: Stop spying on private messages
  aliases:
    - msgunspy
    - aunspy
  subcommands:
    all:
      command: all
      permission: advancedchat.command.unspy.all
      description: Stop spying on all private messages
      aliases: [ ]
    player:
      command: player
      permission: advancedchat.command.unspy.player
      description: Stop spying on a specific player's private messages
      aliases: [ ]
esmignore:
  command: esmignore
  permission: advancedchat.command.esmignore
  description: Ignore player's messages
  aliases:
    - esmaignore
  subcommands:
    esmall:
      command: esmall
      permission: advancedchat.command.ignore.all
      description: Ignore all player's messages
      aliases: [ ]
    esmplayer:
      command: esmplayer
      permission: advancedchat.command.ignore.player
      description: Ignore a specific player's messages
      aliases: [ ]
    esmlist:
      command: esmlist
      permission: advancedchat.command.ignore.list
      description: List all players you are ignoring
      aliases: [ ]
esmunignore:
  command: esmunignore
  permission: advancedchat.command.esmunignore
  description: Stop ignoring player's messages
  aliases:
    - esmaunignore
  subcommands:
    esmall:
      command: esmall
      permission: advancedchat.command.esmunignore.esmall
      description: Stop ignoring all player's messages
      aliases: [ ]
   esmplayer:
      command: esmplayer
      permission: advancedchat.command.esmunignore.esmplayer
      description: Stop ignoring a specific player's messages
      aliases: [ ]
chatcolor:
  command: chatcolor
  permission: advancedchat.command.chatcolor
  description: Change your chat color
  aliases:
    - color
    - colors
    - chatcolors
    - chatcolor
tags:
  command: tags
  permission: advancedchat.command.tags
  description: Change your chat tag
  aliases:
    - tag
    - tags
    - chattags
    - chattag
  subcommands:
    apply:
      command: apply
      permission: advancedchat.command.tags.apply
      description: Apply a tag
      aliases: [ ]
    create:
      command: create
      permission: advancedchat.command.tags.create
      description: Create a tag
      aliases: [ ]
    delete:
      command: delete
      permission: advancedchat.command.tags.delete
      description: Delete a tag
      aliases: [ ]
    list:
      command: list
      permission: advancedchat.command.tags.list
      description: List all tags
      aliases: [ ]
esmwarn:
  command: esmwarn
  permission: advancedchat.command.esmwarn
  description: Warn a player
  aliases:
    - esmawarn

**Comment by DontMessWithDis** [comment]
[commands file.txt](https://github.com/user-attachments/files/15993447/commands.file.txt)

**Comment by DontMessWithDis** [comment]
This one you sent actually disables all commands like /colors etc.

**Comment by ThomasWega** [comment]
I see. You've renamed the actual keys. Don't rename the sections. Only the values inside

**Comment by DontMessWithDis** [comment]
The new update fixed it, thanks!
