### ISSUE TITLE
[item] [inv] [enderchest] [money] [pos] [ping]

### ISSUE THREAD

**Issue by Tolmwn** [AdvancedPlugins/Chat#114]
### Describe the feature

A good i feature is that ppl can use this six things at the chat [item] [inv] [enderchest] [money] [pos] [ping].

- Type [item] in chat to show off the item in your hand!
- Type [inv] in chat to show off your inventory
- Type [ender] and you guessed it! Show your ender chest!
- Type [money] Show the amount  of money you have in the chat.
- Type [pos] Shows your current position.
- Type [ping] Shows your current ping!

![image](https://github.com/AdvancedPlugins/Chat/assets/136921445/7d0d590b-e768-4164-8330-3373fed8c3bb)

I want that the [item] is be show the currect name from the item at the chat and when player get his mouse at the name, then is shows the lore with the enchants and other things that it has.

![image](https://github.com/AdvancedPlugins/Chat/assets/136921445/69ab4d8e-cb37-460f-96d5-048095b81034)

**Comment by Xitryne** [comment]
+1

**Comment by Preddiex** [comment]
+1

**Comment by ThomasWega** [comment]
Will be added in the next update! At least most of them. For the missing ones, we will be working on those
