### ISSUE TITLE
Custom player channels

### ISSUE THREAD

**Issue by Tolmwn** [AdvancedPlugins/Chat#117]
### Describe the feature

You can add a command like /sc so ppl dont need to join and leave from a channel but he can write at the chat /sc and then the messeng that he want only the players from the staff chat see. 

An other idea is that you can add a command like /channel add {name from channel} | /channel remove {name from channel} so they can make channels to speak only with his friends.  Like /msg and /r but that player can speak with more as one player together in same time.

**Comment by ThomasWega** [comment]
Hey! Great suggestion! We have moved suggestions to discord, where community votes on features to be added. Not a lot of people use github. If you are still interested in us adding this feature, please add it in the discord server. Thank you! <3
