### ISSUE TITLE
Add a Gui list for the /reports

### ISSUE THREAD

**Issue by Tolmwn** [AdvancedPlugins/Chat#118]
### Describe the feature

 A gui or list that shows all player /reports together? Because now the command /report it's show only for some seconds at the chat that report and not anymore. Its gonna be more better if that its gonna be a gui with the skull from each player that made report and more info for what its he reported. Like a ticket system, maybe more one feature that he can open tickets if they found any error or bug at the server.

**Comment by ThomasWega** [comment]
Hey! Great suggestion! We have moved suggestions to discord, where community votes on features to be added. Not a lot of people use github. If you are still interested in us adding this feature, please add it in the discord server. Thank you! <3
