### ISSUE TITLE
Vanish support for `msg`

### ISSUE THREAD

**Issue by Schroddinger** [AdvancedPlugins/Chat#12]
## Scenario
Using `/msg` can reveal is a player is online on the server. Some plugins provide a feature to prevent this from happening, but still the `/reply` command still bypasses this feature (if the vanished player has already been sending messages).

Joining and leaving the server also broadcast the player joining and leaving even if they're supposed to be vanished.

## Solution
Some plugins like `SuperVanish` and `PremiumVanish` (at least for Bukkit) hide the "vanish status"
 in the player metadata, so they don't require an API.

Example of how to check the vanish status in kotlin:
```kt
// Settings.Vanish.vanish_meta contains the keyword 'vanished' and is read from my config file
fun isVanished(player: Player): Boolean {
    return player.getMetadata(Settings.Vanish.vanish_meta).any{ it.asBoolean() }
}
```

As for the join event, those plugins offer a way to simulate the player joining/leaving message so no further logic is required, just an `if (isVanished(player)) return`.

## Bungeecord / Velocity
I'm not sure if you have plans of upgrading the plugin to eventually work on the proxy, but handling vanish in this scenario does require an API (If an upgrade like this is planned).
`SuperVanish` and `PremiumVanish` have their API, `VelocityVanish` has its own API as well. It might be a mess supporting every vanish plugin in existence, so may be better to expand the API and provide events for each server owner to manually cancel the `/msg` command or join/leave messages of their networks.

This also will provide support for plugins like `HideME` that doesn't use the player metadata, and thus require an API to work, even if the plugin is not made to work in a proxy.

**Comment by ThomasWega** [comment]
Will be added next update!
