### ISSUE TITLE
Exception while converting NMS ItemStack to NBTCompound

### ISSUE THREAD

**Issue by Atabeyi** [AdvancedPlugins/Chat#120]
When I type [item] in the chat, I get an error and turns default Minecraft chat format.

![javaw_bkLTLLAWsb](https://github.com/AdvancedPlugins/Chat/assets/59102215/289f1b4d-ddac-4fb5-a326-1b965e0a3771)

![Code_PwmsayBmF2](https://github.com/AdvancedPlugins/Chat/assets/59102215/b90ddcb0-3d7d-44d6-af04-16c0501a0e6d)

**Comment by ThomasWega** [comment]
Try on latest now please

**Comment by MonsterMilo** [comment]
I am trying now on the latest version (1.3.5) and this bug is still occuring for me
