### ISSUE TITLE
Emojis break chatcolors if used at the beginning/middle of messages.

### ISSUE THREAD

**Issue by DivineSanta** [AdvancedPlugins/Chat#121]
### Describe the bug

If you put an emojis anywhere in a message that isn't the end while you have a chatcolor enabled, it automatically breaks the rest of the message.

### How to reproduce

Add a chatcolor in game and use any emojis at the beginning or middle of a message.

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/151980648/64fbfd0c-2c7a-4105-8938-6c5b7b4f77a3)
![image](https://github.com/AdvancedPlugins/Chat/assets/151980648/f54a288b-d4e2-4b70-a867-ecadb534ef83)

**Comment by DivineSanta** [comment]
Yes

**Comment by ThomasWega** [comment]
Just tested it out and it seems to work fine. You need to either be resetting the color somewhere or not enclosing the tag properly
