### ISSUE TITLE
Choose which channels to link under the same proxy

### ISSUE THREAD

**Issue by Xeroclon** [AdvancedPlugins/Chat#124]
### Describe the feature

Choose which channels to link under the same proxy

For example, I have 6 servers (A,B,C,D,E,F), if I install the plugin on all my servers right now I could make them share the same channel, but it would be great if I could choose which servers are the ones linked

Server A with B: Only the chat will be shared between server A and B, the others will be excluded.

Server C with D: Here only the chat of server C will be linked to D and other servers will still be excluded.

Server E with F: Here the chat of Server E will be linked to the chat of server F and the chat of the other servers will not be linked to these two servers.

**Comment by ThomasWega** [comment]
Hey! Great suggestion! We have moved suggestions to discord, where community votes on features to be added. Not a lot of people use github. If you are still interested in us adding this feature, please add it in the discord server. Thank you! <3
