### ISSUE TITLE
Emoji bug

### ISSUE THREAD

**Issue by Tolmwn** [AdvancedPlugins/Chat#126]
### Describe the bug

I go warn at the console when i use one from the emoji that the plugin has and the emoji is not working.

### How to reproduce

![image](https://github.com/AdvancedPlugins/Chat/assets/136921445/f8b39109-8121-495c-9c97-1835f663fa9b)

### Screenshots / Videos

https://mcpaste.io/81e2449b957789c1

**Comment by ThomasWega** [comment]
That's error from decentholograms, not us

**Comment by Tolmwn** [comment]
They say that it was not a error from decentholograms but i just update the both plugins and remove the files so its gonna be a full reset for the both plugins and now is still not show the emoji but its removed the error from the console. I dont know what is now wroth !

**My last latest.log:** https://mcpaste.io/606e97f35dd6e70d

**Comment by ThomasWega** [comment]
Will be fixed in the next update
