### ISSUE TITLE
Townychat compatibility

### ISSUE THREAD

**Issue by Xeroclon** [AdvancedPlugins/Chat#128]
### Describe the feature

I loved advancedchat, unfortunately I couldn't leave it on my servers because it doesn't have compatibility with townychat and when I want to use the towny channels like /tc they don't work and the advancedchat are still there even if you leave the advancedchat channel

**Comment by ThomasWega** [comment]
What exactly doesn't work? Provide examples of what you need to be supported. What happens now and what is the expected result?

**Comment by Xeroclon** [comment]
> ¿Qué es exactamente lo que no funciona? Proporcione ejemplos de lo que necesita para recibir apoyo. ¿Qué sucede ahora y cuál es el resultado esperado?

TownyChat works perfectly when AdvancedChat is not there, but when I add AdvancedChat to my server and I want to change to a TownyChat channel, for example to towny chat I use the command to change which is /tc then in the chat it appears that I change correctly to the channel from towny but in the chat messages continue to be sent to everyone and not just to my town, so I would like them to add compatibility with tonwychat and husktown so that their channels work if AdvancedChat is on the server

Examples:

I am in an AdvancedChat channel, the channel is the general channel in this channel all the players on the server read me, I want to move to a TownyChat or HuskTown channel, then I use the corresponding command (/tc) when executing the command I want AdvancedChat let TownyChat and HuskTown work as messages are still being sent with AdvancedChat and the HuskTown and Towny channels are not working


Expected result: That AdvancedChat allows the channels of other plugins such as TownyChat and HuskTown to work since these channels are essential in this type of plugins to communicate only with your allies

**Comment by Moosebobby123** [comment]
Is there any update on this? I am nearing release of my server and I need this feature that was advertised as towny compatible. I will unfortunately have to use another chat plugin otherwise.

**Comment by ThomasWega** [comment]
Next version will be improved compatibility. Apologies for the hold up.
