### ISSUE TITLE
Console Errors & Spam

### ISSUE THREAD

**Issue by DontMessWithDis** [AdvancedPlugins/Chat#129]
### Describe the bug

The console is constantly spamming no matter how many times I update the plugin. 

### How to reproduce

Install the plugin

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/121703064/01beb62c-cee1-449a-b7ec-45cf266d849b)

### Server Log

https://paste.dedimc.io/evijiyuyon

**Comment by ThomasWega** [comment]
Are you 100% sure you are on latest? What's the server version? Is the AdvancedChat on latest on all servers it's used on?
