### ISSUE TITLE
Cannot disable filters

### ISSUE THREAD

**Issue by iandrew1337** [AdvancedPlugins/Chat#136]
### Describe the bug

Adding channels to the **disabledChannels** in **swearing.yml** and **ai.yml** does not seem to do anything. Swearing in the "disabled" channel still gets flagged, and moderation actions are still being taken.

Plugin version: 1.3.1
Minecraft version: Purpur 1.21 (Build 2260)

### How to reproduce

1. Create a channel
2. Add it in both swearing.yml and ai.yml under disabledChannels (Case sensitive)
3. Join that channel and attempt to swear in said channel

### Screenshots / Videos

![what](https://github.com/user-attachments/assets/77cc4255-53ae-4bb3-8cff-d9a80c920eb5)

### Server Log

n/a - there are no errors

**Comment by ThomasWega** [comment]
Will be fixed in the next update
