### ISSUE TITLE
Lot of problem

### ISSUE THREAD

**Issue by Xitryne** [AdvancedPlugins/Chat#137]
### Describe the bug

Players do not see messages when someone logs in or out. When I log in, I see the message but no other player does, and the same goes for the others. I'm talking about the joinMessages file.

### How to reproduce

Login, see login message but other player doesn't (Everyone is OP)

**Comment by Xitryne** [comment]
![2024-07-14_14 34 02](https://github.com/user-attachments/assets/0acc1532-840e-4e9a-bcda-bbb1ade87e20)
My username normally contains a capital letter, but this one doesn't. What's more, my server is French and it's impossible to translate the mini-game blocks, for example

**Comment by Xitryne** [comment]
![2024-07-14_14 42 39](https://github.com/user-attachments/assets/a138a949-88e2-4833-9ab5-0fca3832ea49)
SuperiorSkyblock's placeholders don't work, and the items you want to show don't translate either, and if the item has a custom name it doesn't make any difference. There should be InteractiveChat functionality

**Comment by Xitryne** [comment]
SuperiorSkyblock's placeholders work now*

**Comment by Xitryne** [comment]
When you run /ads reload
and you've modified the prefix in en.yml, it doesn't update, only the messages.

**Comment by Xitryne** [comment]
![2024-07-15_11 56 18](https://github.com/user-attachments/assets/114a5bde-debb-45cb-89d9-4550c9fc53f9)
The player's head in Chat doesn't work properly, after not logging in for a long time, it just says 'Not cached'.

**Comment by ThomasWega** [comment]
> ![2024-07-14_14 34 02](https://private-user-images.githubusercontent.com/53669476/348542875-0acc1532-840e-4e9a-bcda-bbb1ade87e20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDUzMDUsIm5iZiI6MTcyMTA0NTAwNSwicGF0aCI6Ii81MzY2OTQ3Ni8zNDg1NDI4NzUtMGFjYzE1MzItODQwZS00ZTlhLWJjZGEtYmJiMWFkZTg3ZTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEyMDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1Y2M1YjBkODljYjdhNDYxODlhMjNhNDQ2Y2FhNzUzYWU0NGUxMGQ3ZjIyMzE2YmIwOWQ4ZjA5MTQ1N2QxYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vVbzam5wHu2j6IVezPkMcfyd7jdPpLTiB7JddA9IJs8) My server is French and it's impossible to translate the mini-game blocks, for example. What's more, you can't set the time players have to play the mini-game, and there's no way to tell how long it took them to complete it.

You can customize the block display name by just changing the blocks to break. 
![image](https://github.com/user-attachments/assets/f66a019f-94d7-442a-b582-baf80e93f03b)




> When you run /ads reload and you've modified the prefix in en.yml, it doesn't update, only the messages.

fixed




> ### Describe the bug
> 
> Players do not see messages when someone logs in or out. When I log in, I see the message but no other player does, and the same goes for the others. I'm talking about the joinMessages file.
> ### How to reproduce
> 
> Login, see login message but other player doesn't (Everyone is OP)
> ### Screenshots / Videos
> 
> _No response_
> ### Server Log
> 
> _No response_

fixed



> ![2024-07-15_11 56 18](https://private-user-images.githubusercontent.com/53669476/348665038-114a5bde-debb-45cb-89d9-4550c9fc53f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDUzMDUsIm5iZiI6MTcyMTA0NTAwNSwicGF0aCI6Ii81MzY2OTQ3Ni8zNDg2NjUwMzgtMTE0YTViZGUtZGViYi00NWNiLTg5ZDktNDU1MGM5ZmM1M2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEyMDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1OGUzNDI5Yzk5YTk3MmQwMTdhMzJhYjA3ZGE0ZjczNTlkMTdkZjQ4ZWNkNzU4YjUyNmI3ZTE3MTdhMWIzNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.673jY4liOmgYBGn3_HVXIlRHXl9XyAM_jRvhA00IKwY) The player's head in Chat doesn't work properly, after not logging in for a long time, it just says 'Not cached'.

fixed

All next update

**Comment by ThomasWega** [comment]
> ![2024-07-14_14 42 39](https://private-user-images.githubusercontent.com/53669476/348543373-a138a949-88e2-4833-9ab5-0fca3832ea49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDUzMDUsIm5iZiI6MTcyMTA0NTAwNSwicGF0aCI6Ii81MzY2OTQ3Ni8zNDg1NDMzNzMtYTEzOGE5NDktODhlMi00ODMzLTlhYjUtMGZjYTM4MzJlYTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEyMDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMzBiM2ZhNzllYmI4NmNiY2E4OWQzM2VjMzQ2ZWNiYTUwZmFlN2VhNTFmZThmYTYxYTM1NmViZWNiMTVmYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TI1PAXAkR39vj8saibBWdska3wuz2B6VS4YediZr8XY) The items you want to show don't translate either, and if the item has a custom name it doesn't make any difference. There should be InteractiveChat functionality

This is reported in other issue already

**Comment by ThomasWega** [comment]
The join/leave messages are not shown because your OPs have ````advancedchat.ignorejoinformat.FORMAT```. You need to negate that permission

**Comment by Xitryne** [comment]
> > ![2024-07-14_14 34 02](https://private-user-images.githubusercontent.com/53669476/348542875-0acc1532-840e-4e9a-bcda-bbb1ade87e20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDUzMDUsIm5iZiI6MTcyMTA0NTAwNSwicGF0aCI6Ii81MzY2OTQ3Ni8zNDg1NDI4NzUtMGFjYzE1MzItODQwZS00ZTlhLWJjZGEtYmJiMWFkZTg3ZTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEyMDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1Y2M1YjBkODljYjdhNDYxODlhMjNhNDQ2Y2FhNzUzYWU0NGUxMGQ3ZjIyMzE2YmIwOWQ4ZjA5MTQ1N2QxYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vVbzam5wHu2j6IVezPkMcfyd7jdPpLTiB7JddA9IJs8) My server is French and it's impossible to translate the mini-game blocks, for example. What's more, you can't set the time players have to play the mini-game, and there's no way to tell how long it took them to complete it.
> 
> You can customize the block display name by just changing the blocks to break. ![image](https://private-user-images.githubusercontent.com/82312488/348700757-f66a019f-94d7-442a-b582-baf80e93f03b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzQ2NDYsIm5iZiI6MTcyMTA3NDM0NiwicGF0aCI6Ii84MjMxMjQ4OC8zNDg3MDA3NTctZjY2YTAxOWYtOTRkNy00NDJhLWI1ODItYmFmODBlOTNmMDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIwMTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YzlmMWYwNjQ5MmE4MTU1NDFkMGVkYzU3MmYyNjdkYjFjNWRiYjgyMjFlOTcxMjI3ZDYxNGMzMDY2ZDk0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r0ikoPMAlsSrmk4LzthCFARyDyYRnO_Kd0D7wDIvwbc)
> 
> > When you run /ads reload and you've modified the prefix in en.yml, it doesn't update, only the messages.
> 
> fixed
> 
> > ### Describe the bug
> > Players do not see messages when someone logs in or out. When I log in, I see the message but no other player does, and the same goes for the others. I'm talking about the joinMessages file.
> > ### How to reproduce
> > Login, see login message but other player doesn't (Everyone is OP)
> > ### Screenshots / Videos
> > _No response_
> > ### Server Log
> > _No response_
> 
> fixed
> 
> > ![2024-07-15_11 56 18](https://private-user-images.githubusercontent.com/53669476/348665038-114a5bde-debb-45cb-89d9-4550c9fc53f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDUzMDUsIm5iZiI6MTcyMTA0NTAwNSwicGF0aCI6Ii81MzY2OTQ3Ni8zNDg2NjUwMzgtMTE0YTViZGUtZGViYi00NWNiLTg5ZDktNDU1MGM5ZmM1M2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEyMDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1OGUzNDI5Yzk5YTk3MmQwMTdhMzJhYjA3ZGE0ZjczNTlkMTdkZjQ4ZWNkNzU4YjUyNmI3ZTE3MTdhMWIzNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.673jY4liOmgYBGn3_HVXIlRHXl9XyAM_jRvhA00IKwY) The player's head in Chat doesn't work properly, after not logging in for a long time, it just says 'Not cached'.
> 
> fixed
> 
> All next update

I don't know if I understood your message correctly, is it possible to translate the mini-game blocks or not? I'm not talking about changing the blocks, I'm talking about translating them.

**Comment by ThomasWega** [comment]
I've misunderstood the question, apologies. Although still possible, it might be a bit hacky.

Technically, you can do something like this. Provide the translations like so:
![image](https://github.com/user-attachments/assets/a8c2955c-bc3c-4082-af59-4d0cf7d233a5)

then using PlaceholderAPI expansion to format these correctly. Something like this 
![image](https://github.com/user-attachments/assets/93222c41-d848-4823-8df3-7482f68e9c7c)
