### ISSUE TITLE
Several death messages

### ISSUE THREAD

**Issue by Xitryne** [AdvancedPlugins/Chat#138]
### Describe the feature

I have a DeathMessages plugin that contains, for example, for a player who falls
  Fall:
  - '&f%player% &7still having trouble flying'
  - '&f%player% &7learns to fly'
  - '&f%player% &7has slipped'

This makes it possible to diversify messages, and I'd like to have it in AdvancedChat.

**Comment by ThomasWega** [comment]
Next update, you will be able to use list and random message will be selected each time
