### ISSUE TITLE
Add GUI for /report

### ISSUE THREAD

**Issue by Xitryne** [AdvancedPlugins/Chat#139]
### Describe the feature

The /report PLAYER REASON command
command is currently useless - it's just empty space. What's needed is a GUI linked to this, so that when the player reports another player, it records his latest chat messages and we can then look at what the player has written.

**Comment by ThomasWega** [comment]
Hey! Great suggestion! We have moved suggestions to discord, where community votes on features to be added. Not a lot of people use github. If you are still interested in us adding this feature, please add it in the discord server. Thank you! <3
