### ISSUE TITLE
CAP rules 

### ISSUE THREAD

**Issue by SirJben** [AdvancedPlugins/Chat#141]
### Describe the bug

It won't work. Tried all CAPS.

### How to reproduce

https://paste.md-5.net/gifefekaxo

**Comment by Ironsicecream** [comment]
![image](https://github.com/user-attachments/assets/ee89cd68-ce47-47bd-9b57-da07dfb1dea2)
This is the config caps.yml file.

And this is the output.
![image](https://github.com/user-attachments/assets/01c28ccf-f8ed-4583-9204-f6d3e72c203d)
![image](https://github.com/user-attachments/assets/4612c50e-608c-49e6-9e64-b67dc239487f)

However it allows me to write words that are only 4 letters long or only allows caps in chat up to 4 letters.

**Comment by ThomasWega** [comment]
Was fixed last version. You need to update to latest and regenerate your rules files
