### ISSUE TITLE
Add a local channel option

### ISSUE THREAD

**Issue by Raffaaxxxx** [AdvancedPlugins/Chat#142]
### Describe the feature

You can only see channel messages in a certain block radius. It is very useful and is a feature present on several survival servers. Let players have private conversations without having to use the "Tell" command multiple times

**Comment by ThomasWega** [comment]
Maybe this is already possible with hiddenCommands.yml. Try it out

**Comment by ThomasWega** [comment]
There is already a range option for channels. Check channels.yml
