### ISSUE TITLE
Ability to enable/disable more features

### ISSUE THREAD

**Issue by Cuantes** [AdvancedPlugins/Chat#145]
### Describe the feature

Add the ability to more elements of the plugin.

For example:
- using the msg system
- using ignore system
- using warn system
- using spy system
- using chatcolor system
- using tags system

Not saying I want to disable all of them, but currently they override other plugins and adding the ability to choose what you use is very useful.

**Comment by ThomasWega** [comment]
Should all be possible by disabling the commands, which will be added in the next version!
