### ISSUE TITLE
%player_head%

### ISSUE THREAD

**Issue by Xitryne** [AdvancedPlugins/Chat#147]
### Describe the bug

In the console I get this error message after a player joins 
```
“ERROR15:56:32
[AdvancedChat]: The %player_head% service might be down? This will cause lag! Remove the placeholder for the time being.”
```

### How to reproduce

Update to the latest version 1.3.3, restart the server and rejoin

**Comment by ThomasWega** [comment]
Update to 1.3.4. Your hosting might be blocking this

**Comment by Xitryne** [comment]
![2024-07-27_23 53 12](https://github.com/user-attachments/assets/84076609-607b-4423-83fb-0840b20bdce3)

The bug still persists with 1.3.4, but I'm on a dedicated server, so it shouldn't cause any problems.

**Comment by Xitryne** [comment]
With same error
```
ERROR11:50:02
[AdvancedChat]: The %player_head% service might be down? This will cause lag! Remove the placeholder for the time being.
```

**Comment by ThomasWega** [comment]
Something needs to be blocking the connection. You can just remove the placeholder from the en.yml inside lang folder and not worry about this

**Comment by MonsterMilo** [comment]
Does that mean this won't be fixed? Happening for me as well

**Comment by Xitryne** [comment]
I'm starting to regret my purchase personally. I've had to replace the mini-games with the ChatGames plugin and the death messages with DeathMessages because nothing is complete enough apart from the basic TChat system, which Essentials can already do.

**Comment by ThomasWega** [comment]
If it's a bug, it will be fixed for sure. If your hosting blocks the connection, how are we supposted to fix that?

**Comment by MonsterMilo** [comment]
@ThomasWega I'm going to try to contact my host to get the connection whitelisted, what service is used for it?
