### ISSUE TITLE
Display heads Not Rendering

### ISSUE THREAD

**Issue by HarisAli3** [AdvancedPlugins/Chat#148]
### Describe the bug

![image](https://github.com/user-attachments/assets/b1bac5e4-4008-4616-949f-53077e4d2096)
Display Heads Not Rendering in the Gui Menus.
![image](https://github.com/user-attachments/assets/c38db3c0-7923-4c6f-a192-16bcab8f2931)

### How to reproduce

Just Set the Material to Player_Head and add owner . The head will not render.

![image](https://github.com/user-attachments/assets/a24bc72e-006a-4593-bb7b-82f1efa2d52f)

**Comment by GC-spigot** [comment]
Can you send your whole config file? We can test it then :)

**Comment by HarisAli3** [comment]
https://paste.sparked.host/xihivaluta.http

There you go, my config.

**Comment by HarisAli3** [comment]
hello any update??

**Comment by ThomasWega** [comment]
Hey! Try instead of using `owner`, use `head`

**Comment by HarisAli3** [comment]
Hello Any update?

**Comment by HarisAli3** [comment]
Bro bug confirmed but sill no support. Kindly fix it or i will post a bad review of no support.

**Comment by ThomasWega** [comment]
bug fix will be coming out soon. Needed to fix few more important issues first

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Just pushed the fix

**Comment by ThomasWega** [comment]
spigot changed a way how heads are handled, that's why
