### ISSUE TITLE
Chat Tags

### ISSUE THREAD

**Issue by inkdASCENSION** [AdvancedPlugins/Chat#15]
### Describe the feature

- Add ability to disable chat tags command /tags or..

Add more usability to the tags system.

- Make tags easy to add with in-game command and shown preview in chat when entered
- Allow for description of tags?
- Allow for GUI to self adjust on pages needed
- Allow option to only show what player has unlocked or allow player to see all but show a different icon if the tag is locked, server owner choice on how to display the tags to players.

**Comment by GC-spigot** [comment]
Done! https://github.com/AdvancedPlugins/Chat/blob/main/menus/chatTagsMenu.yml
