### ISSUE TITLE
More GUI in Chat Color for more Custom Color

### ISSUE THREAD

**Issue by KingCueio** [AdvancedPlugins/Chat#151]
### Describe the feature

This would let the server owners to have multiple chat custom color or let their players to have their own custom chat color, as the Chat Tag can have More GUI,

**Comment by ThomasWega** [comment]
Hey! Great suggestion! We have moved suggestions to discord, where community votes on features to be added. Not a lot of people use github. If you are still interested in us adding this feature, please add it in the discord server. Thank you! <3
