### ISSUE TITLE
Caps rule not working

### ISSUE THREAD

**Issue by Ironsicecream** [AdvancedPlugins/Chat#152]
### Describe the bug

Hi, I tried changing the percentage multiple times, and even reinstalled the jar file on my server and made a ticket previously but the problem still persists. Please explain how this works for me because I can type a max of 4 letters until it converts the entire msg to lowercase

### How to reproduce

![image](https://github.com/user-attachments/assets/996a524c-7a0e-4312-a2d5-ff6beda2753e)
Here is a screenshot of my config

**Comment by Ironsicecream** [comment]
![image](https://github.com/user-attachments/assets/428ae310-472a-487a-894e-e371aded2a93)
Now Im getting these ugly "not cached" when logging in

**Comment by ThomasWega** [comment]
remove your rules and let the plugin recreate them. On latest version
