### ISSUE TITLE
Discord to minecraft message.

### ISSUE THREAD

**Issue by DrHeretic** [AdvancedPlugins/Chat#153]
### Describe the bug

I followed the guide on making sure discordSRV is working. The issue is discord to minecraft messages are not being received. It is sending messages to the discord from minecraft.

### How to reproduce

Type in discord channel that is linked to the channel in the config.

**Comment by Gerrit-R** [comment]
Having the same Issue

**Comment by ThomasWega** [comment]
Figured out the issue. You need to use the SNAPSHOT build. An update will probably be released soon
https://snapshot.discordsrv.com/

![image](https://github.com/user-attachments/assets/492fc958-5c87-4a01-bc55-280d8797821c)
