### ISSUE TITLE
&#rrggbb HEX doesn't work if it's not all lowercase

### ISSUE THREAD

**Issue by TypicalHost** [AdvancedPlugins/Chat#154]
### Describe the bug

&#RRGGBB HEX doesn't work if it's not all lowercase, so tools like Birdflop using standard uppercase format wont work.

### How to reproduce

Just use birdflop, and leave all the HEX codes capital, and it will look like a bunch of gibberish instead.
Example below
![image](https://github.com/user-attachments/assets/32e7e147-c2c9-4884-8077-f4a22b6ee02b)
1st message is "&#FFFFFFT&#00EAFFF" 2nd one is "&#ffffffT&#00eaffF"

**Comment by ThomasWega** [comment]
Should be fixed in the next update. Thanks for reporting
