### ISSUE TITLE
CrossServerChat

### ISSUE THREAD

**Issue by AquariamcDev** [AdvancedPlugins/Chat#155]
### Describe the bug

I've had this issue happen a few times recently, restarting the server tends to fix it but im wondering what is causing it. We have AdvancedChat on 2 servers but we dont use Cross Server Chat

Error message: <https://pastebin.com/sVU22HB4>

### How to reproduce

N/A

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/7d8c8a33-0e66-498c-8bcc-0a00d43afd95)

**Comment by AquariamcDev** [comment]
But can be replicated by have AdvancedChat on 2 servers on the same network and having players on both servers.

**Comment by ThomasWega** [comment]
Hey! I have completely revamped this logic, so now hopefully should work fine! next update
