### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by ErenAslaNN** [AdvancedPlugins/Chat#156]
### Describe the bug

AdvancedChat gives this error when a player enters the game.

### How to reproduce

Server Version: Purpur 1.21
AdvancedChat Version: 1.3.4

### Screenshots / Videos

https://mcpaste.io/9f3bf4c69849e46d

### Server Log

https://mcpaste.io/9f3bf4c69849e46d

**Comment by ShamusAU** [comment]
Also getting this spammed in my console, with latest version 1.3.5 and Paper 1.21. 

Default config.

**Comment by ThomasWega** [comment]
Hey! I have completely overhauled this part of the code. Should be fixed in the next update
