### ISSUE TITLE
Games issue, no permission or anything for it why it not showing

### ISSUE THREAD

**Issue by Cryptics1999** [AdvancedPlugins/Chat#159]
### Describe the bug

![image](https://github.com/user-attachments/assets/0773b50e-1d77-45b9-bed2-9f075aaee705)

### How to reproduce

- Purpur 1.21 Java
-  1.3.5 AdvancedChat because 1.3.6 was broken so had to use 1.3.5
- Wait for it to pop up for people with admin perms and not normal

**Comment by ThomasWega** [comment]
Hey! It displays completely okay for me. But I am on 1.20.4. Will need to try on 1.21
![image](https://github.com/user-attachments/assets/f75f225a-bcff-4165-bd70-08f46c8ec7a3)

**Comment by Cryptics1999** [comment]
It displays for me also, but only for me not the players
Sendt fra min iPhone

8. aug. 2024 kl. 17:44 skrev ThomasWega ***@***.***>:

﻿

Hey! It displays completely okay for me. But I am on 1.20.4. Will need to try on 1.21
image.png (view on web)<https://github.com/user-attachments/assets/f75f225a-bcff-4165-bd70-08f46c8ec7a3>

**Comment by ThomasWega** [comment]
i have tried on 1.21.1, one player with no permission, one OP and works completely fine. Try regenerating your files

**Comment by Cryptics1999** [comment]
effects:
    - "CONSOLE_COMMAND:advancedchat broadcast &a"
    - "CONSOLE_COMMAND:advancedchat broadcast                                &d&lCHAT GAME"
    - "CONSOLE_COMMAND:advancedchat broadcast &fThe game has ended! &e%player name% &fwas the first to unscramble the word &e%custom_wordtowrite%&f!"
    - "CONSOLE_COMMAND:advancedchat broadcast &a"
    - "CONSOLE_COMMAND:eco give %player name% 250"

figured out a way to fix it for me atleast, just use the broadcast command
________________________________
Fra: ThomasWega ***@***.***>
Sendt: torsdag 8. august 2024 21:31
Til: AdvancedPlugins/Chat ***@***.***>
Kopi: Cryptics1999 ***@***.***>; Author ***@***.***>
Emne: Re: [AdvancedPlugins/Chat] Games issue, no permission or anything for it why it not showing (Issue #159)


i have tried on 1.21.1, one player with no permission, one OP and works completely fine. Try regenerating your files
