### ISSUE TITLE
AdvancedChatEvent

### ISSUE THREAD

**Issue by Schroddinger** [AdvancedPlugins/Chat#16]
## The Request
Some plugins like TrChat or HuskChat offer an event whenever a message is processed by the plugin (inside or, in this case, even outside a channel).
This will make it easy to work with the plugin without capturing the whole `AsyncPlayerChatEvent`, as the plugin event can already hold the necessary information like `channel`. This also prevent having to mess with other plugins.

An example of how TrChat manages it and what information their event contains, [here](https://github.com/TrPlugins/TrChat/blob/v2/project/runtime-bukkit/src/main/kotlin/me/arasple/mc/trchat/module/display/channel/Channel.kt#L136) is the example of TrChat's event.

## For Paper
I've noticed that you're using `AsyncPlayerChatEvent`. I hope the plugin eventually gets the option to use `AsyncChatEvent` when running on Paper (Oraxen does something similar).

**Comment by ThomasWega** [comment]
Hey! I've added `AdvancedChatEvent` and `AdvancedChannelChatEvent` to the api package. Should be available next update
