### ISSUE TITLE
Mention

### ISSUE THREAD

**Issue by Cryptics1999** [AdvancedPlugins/Chat#160]
### Describe the bug

@playername does not mention them in any way

### How to reproduce

Purpur 1.21 Java
1.35 AdvancedChat
do @playername no ping or title popping up to make them get focus

**Comment by ThomasWega** [comment]
Probably a 1.21 issue again

**Comment by ThomasWega** [comment]
Tested on 1.21.1 and works completely normal. Make sure you are on latest plugin version, server jar and try regenerating your files
