### ISSUE TITLE
Killed by player

### ISSUE THREAD

**Issue by Cryptics1999** [AdvancedPlugins/Chat#161]
### Describe the bug

Killed by players doesnt do the causes a unknown death message

### How to reproduce

1.21 Java Purpur
1.3.5 AdvancedChat
Kill someone

**Comment by ThomasWega** [comment]
Probably a 1.20.5+ only issue again. Works fine on 1.20.4. Will need to test newer versions

**Comment by ThomasWega** [comment]
Tested on 1.21.1 and works completely normal. Make sure you are on latest plugin version, server jar and try regenerating your files
