### ISSUE TITLE
Per channel prefix

### ISSUE THREAD

**Issue by Rubyo2000** [AdvancedPlugins/Chat#162]
### Describe the feature

Hi there,

Currently there is the option to configure the format of the channel prefix and either enable it for every channel, or disable it. For my setup, I'd like to request these to become channel specific settings. That way, I'd be able to specify the look of each channel prefix individually and disable it in the channel where I don't want a prefix.

Example of what I'm looking for:

Global chat: No channel prefix
Local chat: '[Local]' as channel prefix
Staff chat: 'Lobby >> [Staff]' as prefix
... 

Thanks in advance :)

**Comment by ThomasWega** [comment]
Hey! Great suggestion! We have moved suggestions to discord, where community votes on features to be added. Not a lot of people use github. If you are still interested in us adding this feature, please add it in the discord server. Thank you! <3
