### ISSUE TITLE
Swearing

### ISSUE THREAD

**Issue by Xitryne** [AdvancedPlugins/Chat#164]
### Describe the bug

Hello,
I put my github link in the swearing.yml file but the github link keeps changing. How can I prevent it from changing because I have to replace it each time?

### How to reproduce

I

**Comment by ThomasWega** [comment]
What do you mean that it keeps changing? Do you mean that when you replace our link with yours, it's rolled back to the default one?

**Comment by Xitryne** [comment]
No, I'm talking about my github link, it's private but part of the link changes every day. I don't know much about github, how can I make sure the link never changes? (It's private)

**Comment by ThomasWega** [comment]
It doesn't have to be on github. It can even be self hosted. Just make sure it points to a json file with an array. Check out how this one looks
https://raw.githubusercontent.com/AdvancedPlugins/Chat/main/swear%20words/en.json
