### ISSUE TITLE
Cant Use Colors With Placeholders

### ISSUE THREAD

**Issue by ImOpaque** [AdvancedPlugins/Chat#165]
### Describe the bug

Hello, I'm trying to use gradients in chat.

It seems that whenever I use any color besides a simple 1 color (<red>) the placeholder doesn't get colored.

It says %message% with the gradient or effect I use. but will only say that every single time and not translate my message.

This was a key reason I had purchased AdvancedChat, to use gradients in chat formats.

### How to reproduce

In a chat format file, use a gradient or <rainbow> in the chat section. Color the %message% placeholder.

### Screenshots / Videos

![Screenshot 2024-08-06 135513](https://github.com/user-attachments/assets/3733815a-8306-4d71-802c-f692d6055e30)

**Comment by ThomasWega** [comment]
Will be fixed in the next update
