### ISSUE TITLE
Ignore

### ISSUE THREAD

**Issue by Cryptics1999** [AdvancedPlugins/Chat#167]
### Describe the bug

![image](https://github.com/user-attachments/assets/f3bcdce8-6146-4b3a-adb5-6802ac8ff5dc)

When you ignore someone it does not ignore them

### How to reproduce

Purpur 1.21
Ignore
still talking

**Comment by ThomasWega** [comment]
ignore only works for private messages
https://github.com/AdvancedPlugins/Chat/issues/131
