### ISSUE TITLE
chat game 1.21

### ISSUE THREAD

**Issue by Courone** [AdvancedPlugins/Chat#169]
### Describe the bug

Hello, I have a problem in 1.21 with the chat game, we the operators and admins have the messages and we can play the chat game but the players cannot see them.

### How to reproduce

Start the server under paper 1.21

Start an automatic chat game and players do not see the message in the in-game chat

Ops and admins see the chat game in the chat

### Server Log

https://mclo.gs/b0uAcEK

**Comment by GC-spigot** [comment]
I believe this is solved. For future reference - do not remove bukkit's broadcast permission
