### ISSUE TITLE
Announcement channels

### ISSUE THREAD

**Issue by c11network** [AdvancedPlugins/Chat#17]
### Describe the feature

Send specific messages to specific channels that can be joined or left.
For example, have an auctions/tips/trading channel with all those messages from different plugins going to it so that if you are not interested, you don't have to join that channel.
Events like deaths or joins/leaves can be shoved to a server-events or events channel so that it makes the chat cleaner.
Have channels based on perms and autojoin if you are new to the server you get added to the newbie channel where you can ask questions of the server or how to play.
Examples:
Auction
Deaths
Events
Help
Newbie
Tips
Trading
Filter by contains or regex to send those messages just to that channel.

Thank you for reading!

**Comment by BabyKyo** [comment]
Would be like settings! Should be a nice feature to see, would allow each player to clear their chat and informs all of the new players

**Comment by ThomasWega** [comment]
Hey! Great suggestion! We have moved suggestions to discord, where community votes on features to be added. Not a lot of people use github. If you are still interested in us adding this feature, please add it in the discord server. Thank you! <3
