### ISSUE TITLE
Itemshow with interactivechat

### ISSUE THREAD

**Issue by Cryptics1999** [AdvancedPlugins/Chat#171]
### Describe the bug

![image](https://github.com/user-attachments/assets/e34b05c6-f992-4845-a1a4-a5e454820ea2)

When using Interactivechat it has some errors with name 

https://www.spigotmc.org/resources/interactivechat-show-items-inventory-in-chat-custom-chat-keywords-bungee-velocity-support.75870/

### How to reproduce

https://www.spigotmc.org/resources/interactivechat-show-items-inventory-in-chat-custom-chat-keywords-bungee-velocity-support.75870/
Use this and disable the AdvancedChat itemshow

**Comment by ThomasWega** [comment]
Try now on latest please
