### ISSUE TITLE
Emoji bug

### ISSUE THREAD

**Issue by FaiqGaming** [AdvancedPlugins/Chat#172]
### Describe the bug

hello sir i want to use the emoji but didn't work i was type the "\<3" or "\*yes\*" still didn't work

### How to reproduce

The problem is that when I try to use the emoji, it doesn't work when typing the love sign or shrug, etc.

### Screenshots / Videos

https://media.discordapp.net/attachments/1272493308899364864/1272493467863482449/image.png?ex=66bbd624&is=66ba84a4&hm=f2f5df4ad42f79e5fdd3ec41a7dd02598a20e29d108e3346d8be0dcbba1ba34c&=&format=webp&quality=lossless&width=862&height=168

**Comment by GC-spigot** [comment]
Solved
