### ISSUE TITLE
After Update from 1.3.9 to 1.4.1 playernames will be shown like this: {name} died.

### ISSUE THREAD

**Issue by Gerrit-R** [AdvancedPlugins/Chat#175]
### Describe the bug

After Update from 1.3.9 to 1.4.1 playernames will be shown like this: {name} died.

### How to reproduce

Updated from 1.4.1 ind PaperMC 1.21.1. After Updating the Plugins it was happen.

### Screenshots / Videos

![2024-08-24_11 30 02](https://github.com/user-attachments/assets/9d48f5cc-54d8-4f0f-8924-0803dbaba343)

### Server Log

https://mcpaste.io/7a1a1202362d3312

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Thanks for reporting
