### ISSUE TITLE
Spam in the console when I switch to the second server

### ISSUE THREAD

**Issue by mrWezyr** [AdvancedPlugins/Chat#179]
### Describe the bug

I have 2 servers connected by a velocity proxy server. If I join 1 server everything is normal, when I switch to the second server, warnings and spam appear on both servers.

### How to reproduce

Latest 1.21.1 Paper
AdvancedChat 1.4.2
1. Login to first server 
2. Change /server ServerName 

### Screenshots / Videos

![firefox_zrupo2Cpb5](https://github.com/user-attachments/assets/c1a31f8a-33a0-43c2-af92-0206727dc154)

### Server Log

https://mcpaste.io/5e14a8fe1b9d58ec

**Comment by mrWezyr** [comment]
Yes, i have AdvancedChat 1.4.2 on both servers

**Comment by ThomasWega** [comment]
Should be fixed in the next update
