### ISSUE TITLE
DiscordSRV

### ISSUE THREAD

**Issue by Z3r0xh** [AdvancedPlugins/Chat#18]
### Describe the feature

Could full integration with DIscordSRV be added? so that the channels that are created can be added to discordSRV and the "normal" channel is the global one for discordSRV

**Comment by Z3r0xh** [comment]
Hi, do you know when this option can be added?

**Comment by DontMessWithDis** [comment]
I would love integration for discordsrv!

**Comment by ThomasWega** [comment]
Hey! I've just finished the code for this. Update will come soon.
