### ISSUE TITLE
Add placeholder

### ISSUE THREAD

**Issue by BabyKyo** [AdvancedPlugins/Chat#180]
### Describe the feature

Add a placeholder: %advancedchat_hastag_selected%

Would return true or false if a player has a tag selected. This would allow us to make javascripts using papi to return player's group if player doesn't have a tag equiped 

```
var advancedchat = "%advancedchat_hastag_selected%";

function tags() {

   if (advancedchat === "true") {
       return "%advancedchat__tag%";
   }

   else {
       return "%vault_prefix%";
   }
}

tags();
```

**Comment by ThomasWega** [comment]
You could check just for %advancedchat_tag%. If it's empty
