### ISSUE TITLE
Disable/Enable announcements

### ISSUE THREAD

**Issue by BabyKyo** [AdvancedPlugins/Chat#181]
### Describe the feature

Since there is automatic announcement it would be nice to have a way for players to disable/enable them

**Comment by HarisAli3** [comment]
Would be good to have it.

**Comment by ThomasWega** [comment]
Hey! Great suggestion! We have moved suggestions to discord, where community votes on features to be added. Not a lot of people use github. If you are still interested in us adding this feature, please add it in the discord server. Thank you! <3
