### ISSUE TITLE
Double Messages

### ISSUE THREAD

**Issue by Vortex4U98** [AdvancedPlugins/Chat#183]
### Describe the bug

just tried to create a global group and i have the same channels.yml config on both servers

 gb: #Staff chat
    name: 'Global'
    # %channel_color%
    color: "<green>"
    # Whether channel text should always be visible even when not in channel? You must have channel permission
    alwaysVisible: true
    # Only send to players in the same world
    sameWorld: false
    # Whether to use cross-server chat
    crossServer: true
    # Channel messages range
    # If set to 0, range won't be enabled. Set to any other number to enable.
    range: 0
    # Lowest priority will come first
    priority: 1

### How to reproduce

i have no clue

### Screenshots / Videos

![Screenshot 2024-08-29 214256](https://github.com/user-attachments/assets/2707117e-b591-4113-aab6-8a7e111c4fa0)
![Screenshot 2024-08-29 214025](https://github.com/user-attachments/assets/007d4649-296e-4724-bd3e-25d350b77332)

**Comment by ThomasWega** [comment]
Should be fixed in the next update

**Comment by MisterMakey** [comment]
AdvancedChat-1.5.6.jar
Same Problem:
<img width="264" alt="Screenshot_496" src="https://github.com/user-attachments/assets/f3c92c60-f4e3-4b1d-b8e9-6cabb8575457">
