### ISSUE TITLE
Add a nick feature in the plugin

### ISSUE THREAD

**Issue by Cryptics1999** [AdvancedPlugins/Chat#185]
### Describe the feature

Add a nick system in the plugin using Minimessaging so they can use Gradients etc

**Comment by HarisAli3** [comment]
Yes, Please.

**Comment by ThomasWega** [comment]
Hey! Great suggestion! We have moved suggestions to discord, where community votes on features to be added. Not a lot of people use github. If you are still interested in us adding this feature, please add it in the discord server. Thank you! <3
