### ISSUE TITLE
Allow the click open url function in custom commands and allow hex colors.

### ISSUE THREAD

**Issue by Vehzx** [AdvancedPlugins/Chat#187]
### Describe the feature

The click function to open URLs does not work if used within a custom command with the "MESSAGE:" effect.

HEX colors also do not work within the message effect for custom commands.

![image](https://github.com/user-attachments/assets/8a80f0a3-80fc-484c-a327-907e7f819a57)
![image](https://github.com/user-attachments/assets/304f0121-c6fb-493a-9716-db13fe13ce65)

**Comment by GC-spigot** [comment]
Abilities system does not support minimessage formats yet! This will be added soon :)
