### ISSUE TITLE
Discord SRV Issue (Same Goes for EssentialsXDiscord Chat)

### ISSUE THREAD

**Issue by HarisAli3** [AdvancedPlugins/Chat#188]
### Describe the bug

I am trying to connect DiscordSRV with my server. I can see the player leave / join logs but not the messages. AdvancedChat is overriding the messages (so its not showing on discord). I can send messages from discord to Minecraft.

### How to reproduce

Use DiscordSRV with AdvancedChat. or EssentialsXDiscord with AdvancedChat.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/ef07250d-1a76-4258-a9ad-cc22ade8db8a)

**Comment by HarisAli3** [comment]
I am using 1.4.5 Version of AdvancedChat.

**Comment by ThomasWega** [comment]
try latest snapshot of DiscordSRV (https://snapshot.discordsrv.com/) and make sure you have fully followed this guide https://chat.advancedplugins.net/main/plugin-integrations/discordsrv

**Comment by HarisAli3** [comment]
Already tried that with latest snapshot version and did all steps of the guide.

**Comment by ThomasWega** [comment]
So, if I understand correctly, messages sent from minecraft are not shown in discord?

**Comment by HarisAli3** [comment]
But you can see messages that are send from Discord to Minecraft.

**Comment by HarisAli3** [comment]
hlo

**Comment by HuzaifaMughal0024** [comment]
Same issue for me too

**Comment by ThomasWega** [comment]
Works completely fine. You are probably in a channel in minecraft
![image](https://github.com/user-attachments/assets/9b1c0338-30cb-407f-8a38-91a17a9000d0)

**Comment by ThomasWega** [comment]
These need to be declared as on the wiki. With the exact same id as they are setup with
![image](https://github.com/user-attachments/assets/ae94d1c6-43cb-4725-a967-db8740860673)
