### ISSUE TITLE
[API] AdvancedChannelChatEvent not being called

### ISSUE THREAD

**Issue by Schroddinger** [AdvancedPlugins/Chat#189]
### Describe the bug

I think the `AdvancedChannelChatEvent` is not being called, no event listener for `AdvancedChannelChatEvent` is executed.
On the contrary, `AdvancedChatEvent` works perfectly.

### How to reproduce

Create a small plugin using `AdvancedChannelChatEvent` to print a single line in console.

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
