### ISSUE TITLE
Placeholder showing the player reading the message instead of the one actually leaving

### ISSUE THREAD

**Issue by Schroddinger** [AdvancedPlugins/Chat#19]
## Original bug
The original bug I reported was already patched. Originally both joining and leaving messages shown the player reading the message. The joining message was patched however, the leaving message is still showing the player reading the message.

I already commented the new issue the day the original one was patched, I'm just creating this ticket so you can keep track of it.

## To reproduce
Join the server with two accounts
Leave the server using the first account
Read the message with the second account

![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/9f132d87-fd32-442c-a9ca-b14de1636b66)
As mentioned, the joining message works fine, just the leaving message is not ok.

**Comment by GC-spigot** [comment]
Hi, yes that's going to be fixed today in an update in ~2 hours :)

**Comment by Schroddinger** [comment]
Thx! This is indeed fixed now!
