### ISSUE TITLE
Chat filter alerting staff

### ISSUE THREAD

**Issue by Thenorth-s** [AdvancedPlugins/Chat#190]
### Describe the bug

Basically when someone triggers the chatfilter the players word gets deleted and the plugin take actions tho when I'm looking at the console while someone is swearing the plugin is trying to alert staff with the command **alertstaff** tho there isnt a command like that as far as i know the command is **alert** please fix this issue because i want to use that feature :D

### How to reproduce

Just have the console and your minecraft visible on your screen then trigger the chatfilter  and if you watch the console there will be a alert like there is no command named alertstaff

**Comment by ThomasWega** [comment]
rules/swearing.yml. You can change it there

![image](https://github.com/user-attachments/assets/5eda686e-3e98-4b1e-851d-4fd11311e120)
