### ISSUE TITLE
Option to disable commands

### ISSUE THREAD

**Issue by L8-Alphine** [AdvancedPlugins/Chat#193]
### Describe the feature

Add Official support for litebans and to disable the builtin moderation system like the `/warn`, `/mute`, etc from the plugin itself if spigot/paper, or bungeecord/velocity litebans or another moderation based plugin is detected.

This would help with plugin conflicts a lot.

**Comment by HarisAli3** [comment]
Yes add that i am using litebans too.

**Comment by ThomasWega** [comment]
Added option to disable commands in commands.yml
