### ISSUE TITLE
[Item] Show custom item names

### ISSUE THREAD

**Issue by RaidLabsMC** [AdvancedPlugins/Chat#194]
### Describe the feature

https://gyazo.com/310db0f76d655ec3c58b29496d1630db whenever i try to item something it says what the item is instead of giving the custom name for the item. I would like an option to let players use custom names in chat

**Comment by RaidLabsMC** [comment]
if the item you are trying to show off in chat using [item] is a custom name i would like it to show that custom name instead of just saying the item you are holding. players love to show off the names of their item

**Comment by ThomasWega** [comment]
Will be added in the next update
