### ISSUE TITLE
DISCORDSRV conflicts with Essentials

### ISSUE THREAD

**Issue by LilCloud420** [AdvancedPlugins/Chat#195]
### Describe the bug

When installing and fully setting up every aspect of what was necessary for discordsrv to work based on your wiki. And when not being in any channel aside from the main default global channel. all of my join, leave, server start, server stop, and deaths are displayed to discord from minecraft. all messages from discord are being sent to minecraft chat. But no messages from minecraft are going to discord. I have the proper channel id set up, if that was not the case then the messages from discord would not be going to chat. as soon as i remove advancedchat from my server the issue is no longer present. and upon reinstalling and testing the issue is back. once again this is not an issue with discordsrv setup nor is it an issue with my version as i have downloaded the snapshot reccomended. server version is 1.20.1 if this has anything to do with it. also running /discordsrv brodcast works as well.

### How to reproduce

install advancedchat with discordsrv on minecraft version1.20.1. 

### Server Log

https://mclo.gs/1U7ZwiP

**Comment by HarisAli3** [comment]
Still Same Issue, My Previous post got closed. I have setup same channel ids and followed all the steps from the wiki.

**Comment by ThomasWega** [comment]
I will test it once more

**Comment by ThomasWega** [comment]
https://github.com/user-attachments/assets/af35f796-f1e9-4380-a1f7-f355d6ee1c97

**Comment by HarisAli3** [comment]
We are using only default channel (ig thats the issue) and you are testing with staff channel only.

**Comment by HarisAli3** [comment]
![image](https://github.com/user-attachments/assets/26ee36d5-8fb1-434e-86cd-df8df47cdfec)

![image](https://github.com/user-attachments/assets/0791c619-9038-4b05-8bac-74f584da466f)

**Comment by LilCloud420** [comment]
I will record a video using the same layout you have used to prove to you that this is an issue on my lunch break today. I know I have everything set up properly on my end so if we can’t find a solution my best solution will just be removing advanced chat as a whole.

**Comment by LilCloud420** [comment]
You are also testing in Minecraft version 1.21. I said version 1.20.1 it could be a version specific issue. So at least try using all the information that was given before marking the bug as unable to reproduce

**Comment by LilCloud420** [comment]
> ![image](https://private-user-images.githubusercontent.com/99520506/369632477-26ee36d5-8fb1-434e-86cd-df8df47cdfec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzYzMDEsIm5iZiI6MTcyNjkzNjAwMSwicGF0aCI6Ii85OTUyMDUwNi8zNjk2MzI0NzctMjZlZTM2ZDUtOGZiMS00MzRlLTg2Y2QtZGY4ZGY0N2NkZmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDE2MjY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYjA1MDliYWMwMzBkNTAxZGY3Yzg5NmUxODg5NTE5ZTlkMmMwN2I2YmM1NjUxYjcxZDZjYTNkZTQ5ZmRjOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0sXSFLeC1IJ80vr325JLnZI6O7NTjZcY0JyksJBrX94)
> 
> ![image](https://private-user-images.githubusercontent.com/99520506/369632500-0791c619-9038-4b05-8bac-74f584da466f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzYzMDEsIm5iZiI6MTcyNjkzNjAwMSwicGF0aCI6Ii85OTUyMDUwNi8zNjk2MzI1MDAtMDc5MWM2MTktOTAzOC00YjA1LThiYWMtNzRmNTg0ZGE0NjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDE2MjY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZTJhZGY3MDY2Mjk2NDBhMjM4ZWRiZWQzOTBmYzgzYjEyMGM5Zjg4OTkwOTVkODg1NzVkYzVkNmZhMzZlYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J53YzYTQb-FmeNdhJkboSTPUfnsX1rVJURcyP5FfU1M)

This is chat formats not channel information. So I’m not sure what that has to do with the issue.

**Comment by ThomasWega** [comment]
https://github.com/user-attachments/assets/6fb8c156-12ca-4e6d-b07c-65d00188b6cf

**Comment by ThomasWega** [comment]
The only thing I am able to confirm is that advancedchat channel discord -> mc doesn't work, which I am noting and will work on a fix

**Comment by ThomasWega** [comment]
Your issue was minecraft going to discord though. Which works completely fine on my end

**Comment by LilCloud420** [comment]
> Your issue was minecraft going to discord though. Which works completely fine on my end

Yes. But you tested from within the staff channel. I’m talking about global messages not going to discord from Minecraft. Even when I have it set properly in the discordsrv config as this is the main issue. And the reason I know I have the right discord channel set for global is because if tht wasn’t the case the join and leave messages ect would not appear in discord.

**Comment by LilCloud420** [comment]
And you also never tested on a server that is Minecraft 1.20.1 you tested on Minecraft 1.21.1

**Comment by LilCloud420** [comment]
Why are you changing my ticket post. To something that isn’t even the issue I’m bringing up right now.

**Comment by LilCloud420** [comment]
Rather than trying to prove to me that I’m wrong how about you actually try to find the information needed to solve he problem

**Comment by LilCloud420** [comment]
Horrible dev team smh

**Comment by LilCloud420** [comment]
Is there at least a way to completely disable the stupid channel aspect of your plugin because that’s probably the only thing causing issues

**Comment by ThomasWega** [comment]
I've tested on spigot 1.20.1 in the latest video. I've also tested staff channel and global messages. I have changed the title so far to make sure that at least the bugs we were able to identify yet are being tracked

**Comment by LilCloud420** [comment]
Once I get on to my lunch break I will send you a video as I have stated. That will prove that I’m not an idiot as you seem to think

**Comment by LilCloud420** [comment]
Can’t you just forward this ticket to someone who actually cares to help

**Comment by LilCloud420** [comment]
And don’t change the name of my ticket. If you want to add a new bug then make a new ticket and stop changing mine

**Comment by ThomasWega** [comment]
> Once I get on to my lunch break I will send you a video as I have stated. That will prove that I’m not an idiot as you seem to think

The only one insulting anyone here is you insulting me. I am trying to go above and beyond testing anything I can. How would you approach this when you are not able to replicate the issue?

**Comment by LilCloud420** [comment]
Because this entire time you are only trying so hard to say there are no issues rather than listening to us and trying to help. You literally closed the lst persons ticket and still haven’t answered half of the things I have asked

**Comment by LilCloud420** [comment]
The whole reason I worded my Initial ticket as I did was to avoid with dealing with you acting like there’s nothing wrong with your oh so perfect plug-in when there obviously is. Deleting the Olguín i have no issues. Resinstalling they return. I will literally send you a video but you have to wait til I go to lunch.

**Comment by ThomasWega** [comment]
Essentials cause this

**Comment by LilCloud420** [comment]
> Essentials cause this

So with that being said. Is this something you guys would recommend the removal of essentials for? Or would y’all just work an update to solve the issue in the future?

**Comment by ThomasWega** [comment]
I will definitely be trying to find a fix

**Comment by HarisAli3** [comment]
Bro, any update on this ???? Players are asking for it since last eternity :((

**Comment by ThomasWega** [comment]
We have updates queued. Doesn't mean we are not looking into this. This is a hard one to figure out. It will be fixed soon

**Comment by ThomasWega** [comment]
Issue was figured out. Update will be released very soon
