### ISSUE TITLE
The commands /color /tags do not work v.1.21

### ISSUE THREAD

**Issue by ExtraAndi** [AdvancedPlugins/Chat#197]
### Describe the bug

When I try to use the /tags or /color commands on my 1.21 server I get an error !I mention that I also installed the latest version of 1.4.9 and it is the same! 

### How to reproduce

[message.txt](https://github.com/user-attachments/files/17099433/message.txt)

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/44a422d9-6af0-4619-bba8-b56b1b07c45a)

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Mojang or Spigot changed how skulls are handled for no reason whatever
