### ISSUE TITLE
per channel lock chat

### ISSUE THREAD

**Issue by Kyphers** [AdvancedPlugins/Chat#2]
### Describe the feature

a way for adminstrators to lock a certain channel so no players can send messages unless they have the specific channel bypass permission or global bypass permissions.

**Comment by MakeItReaal** [comment]
+1

**Comment by Sp00kableDev** [comment]
+1

**Comment by ThomasWega** [comment]
Hey! Great suggestion! We have moved suggestions to discord, where community votes on features to be added. Not a lot of people use github. If you are still interested in us adding this feature, please add it in the discord server. Thank you! <3

**Comment by MakeItReaal** [comment]
Dear @ThomasWega,

I'm not able to make the request on discord since I dind't buy the plugin yet since i wanted to wait for a few suggestions.
