### ISSUE TITLE
Console Spam & /chatcolor not working (head bug?)

### ISSUE THREAD

**Issue by Stormbold** [AdvancedPlugins/Chat#200]
### Describe the bug

/chatcolor doesnt open

Console spam with null

### How to reproduce

Paper 1.21.1 Version 98
Latest Plugin from Spigot

### Screenshots / Videos

![2024-09-24_23 02 59](https://github.com/user-attachments/assets/6210fd31-bee4-4f64-b30a-d3b433c9f0f9)

### Server Log

https://mcpaste.io/3212efa6bb7a6de5 https://mcpaste.io/773a2e1daa63390c

**Comment by GC-spigot** [comment]
Solved on latest
