### ISSUE TITLE
/mute does not work for the Advancedban plugin

### ISSUE THREAD

**Issue by ExtraAndi** [AdvancedPlugins/Chat#203]
### Describe the bug

Hello, I have a problem with advanced mute... until I had the advanced chat plugin, when I muted the player, it got muted.. but since I have the advanced chat plugin, even if I mute the player, it can write... even if it is muted.. can you help me to solve this bug?

### How to reproduce

When I put /mute or /tempmute the player can bypass this command and write normally on the chat!

**Comment by ThomasWega** [comment]
AdvancedBan is cancelling the event on HIGHEST priority, which is basically the same as us, so we probably run first before it cancels the events. They should preferably run it on LOW, or you need to change the priority in our config.yml 
![image](https://github.com/user-attachments/assets/bb446208-bfb3-415d-9856-1de27ba583ec) to MONITOR, but that is not really suggested and could cause other issues
