### ISSUE TITLE
ERROR in console

### ISSUE THREAD

**Issue by Xitryne** [AdvancedPlugins/Chat#204]
### Describe the bug

I disabled everything in the channels config file and apparently the plugin didn't like it.

### How to reproduce

I disabled everything in the channels config file and apparently the plugin didn't like it.
```
# Chat Channels
# Permission: advancedchat.channel.join.<channel>
# Permission: advancedchat.channels to list channels using /channels command
# Permission: advancedchat.channel.autojoin.<channel name> to auto join channel on join
# Permission: advancedchat.channel.leave.<channel> to have channel leave permission

# Should player automatically join an available channel on join?
autoJoin: false

prefix: []

quickMessage: []

channels: []
```

An enabled/disabled option at the top of the config would be welcome

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/4cb0c287-2788-42f8-b03d-d75a5d0e3b85)

**Comment by ThomasWega** [comment]
You cannot just delete whatever you like and then complain to us. Reset your files and have the strings empty. Don't delete them
