### ISSUE TITLE
Can't put colors in /discord command

### ISSUE THREAD

**Issue by Yertled** [AdvancedPlugins/Chat#205]
### Describe the bug

So I started testing with the /discord command, and it's not working. 
I have tried these:
&#HEX
#HEX
<#HEX>
<color:#HEX>

### How to reproduce

![image](https://github.com/user-attachments/assets/0c45e8e3-c507-4e61-89e6-10d89ca9a027)
![image](https://github.com/user-attachments/assets/3af32d7d-9569-444b-ae9d-bc35ad9c42ed)
![image](https://github.com/user-attachments/assets/10148d0b-b902-40f6-a772-db7d822e5e34)
![image](https://github.com/user-attachments/assets/21cd0143-ea8b-40ec-b3ee-0d3cca094b43)
![image](https://github.com/user-attachments/assets/19cb5499-964f-4142-a6a2-d250b65fc0d0)
![image](https://github.com/user-attachments/assets/f61dde53-48db-4fb8-9a0d-512277d325af)

**Comment by ThomasWega** [comment]
This is abilities. They don't support minimessage yet

**Comment by ThomasWega** [comment]
We are already working on implementing minimessage, don't worry
