### ISSUE TITLE
bypass is broken

### ISSUE THREAD

**Issue by tantaf123** [AdvancedPlugins/Chat#208]
### Describe the bug

Advanced chat bypass permissions don't work, even if you have the bypass permission, you still get warned.
![image](https://github.com/user-attachments/assets/e4efcef9-8702-4678-a624-75548176b24f)

### How to reproduce

.

### Screenshots / Videos

https://gyazo.com/42ce481389614b871fc7af61c5394b7c

### Server Log

a

**Comment by ThomasWega** [comment]
you might not be bypassing rules? But you seem to be using the correct wildcard. I will test it out
![image](https://github.com/user-attachments/assets/1e356446-6529-48a1-b1f2-754aadd30308)

**Comment by ThomasWega** [comment]
Will be fixed in the next update
