### ISSUE TITLE
Double Messages  AdvancedChat-1.5.6.jar

### ISSUE THREAD

**Issue by MisterMakey** [AdvancedPlugins/Chat#209]
<img width="264" alt="Screenshot_496" src="https://github.com/user-attachments/assets/b8b440dd-a265-436a-9055-dbe2b59af2a3">
### Describe the bug

We have a double chat that we can't get rid of.

Minecraft 1.21.0 Velocity Server

### How to reproduce

This happens when multiple players are on one server. The chat messages always appear twice. The GlobalChat works normally, so other players on a different server see the chat as expected.

**Comment by Taiyou06** [comment]
Can reproduce it as well
![image](https://github.com/user-attachments/assets/c41f7919-87ac-414f-8172-36b5d285ae73)

**Comment by ThomasWega** [comment]
Handling this issue further on discord with one of you already. Will finish it there

**Comment by Nezoy** [comment]
have the same issue on Velocity 1.21.4

So I bought the plugin today and installed it, I do have a Velocity and some Sub-servers.
When I enable the crossserver feature in the formats, messages will double. But only if you're in the same server and if someone is in another server it won't. Also the person who sends the message won't see it double too. Only the receivers.

I do have Velocity 3.4.0-SNAPSHOT #458 and paper-1.21.4-30
on all sub-servers (lobby, creative, skyblock....) are different plugins, but none of these should edit the chat.

the config's are all the same in each server except the format's
