### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by heykiditsaaron** [AdvancedPlugins/Chat#21]
### Describe the feature

Honestly, I really like this plugin, just want to put that out there first.

I think it would be really neat, although admittedly I have no idea how to make it work, if there was a way to set up inheritance for the formatting of chat. 

For example:
In **default.yml**, I could set *name* and *message* to be %player_name% and %message%, respectively. Then I could go to **mod.yml** and just delete the *name* and *message* sections, and they would inherit it from **default.yml**.

I tried doing something like this already, but didn't get expected results. It may already be possible, and I just have no idea how to do it. If it's not already possible, and not to difficult to make possible, I think this would be a nice feature to save from having to do a fair amount of repetitive work.

**Comment by ThomasWega** [comment]
Hey! I think I understand what you mean, however I cannot see this working reliably without confusing not so tech oriented people like us. You are probably better of just replacing these values manually.
