### ISSUE TITLE
Adveritising bug

### ISSUE THREAD

**Issue by SirJben** [AdvancedPlugins/Chat#210]
### Describe the bug

This bug only works on fresh generated file or fresh installed.

### How to reproduce

Get the latest achat, delete existing AChat folder, install and restart. 

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/df158ff8-73e7-452e-a2a4-35ee2c9659b6)

**Comment by Nodek1984** [comment]
Same issue for me on Windows and on Linux Debian with paper-1.21.1-128

**Comment by ThomasWega** [comment]
1.5.6 should fix this. What version were you on?

**Comment by SirJben** [comment]
> 1.5.6 should fix this. What version were you on?

1.5.7

**Comment by ThomasWega** [comment]
Should be fixed in the next update
