### ISSUE TITLE
 Problems with the AdvancedChat

### ISSUE THREAD

**Issue by frknmrl** [AdvancedPlugins/Chat#211]
### Describe the bug

* Also, some changes I made to the plugin in-game don't work despite using the /achat reload command and require me to restart the server. For example text expressions in the variables file

* The /ignore command doesn't work either, players can use it and block each other, but they still see the messages of the person they blocked, so nothing changes

* It would also be nice to be able to reset the chat colors of the players, I couldn't find anything about this in the plugin file.

* Changes I made in chat games also won't reload despite using the /achat reload command

* When I click on the player message, the player name does not appear, it appears as /report %player_name% 
(PlaceholderAPI Installed on My Server)

### How to reproduce

My server is on version 1.21.1 and uses Paper

**Comment by ThomasWega** [comment]
I will test everything and let you know.

I think this has been already added, but it might not been pushed to prod yet

> * The /ignore command doesn't work either, players can use it and block each other, but they still see the messages of the person they blocked, so nothing changes

**Comment by ThomasWega** [comment]
> * For example text expressions in the variables file

fixed in the next update

**Comment by ThomasWega** [comment]
> * It would also be nice to be able to reset the chat colors of the players, I couldn't find anything about this in the plugin file.

![image](https://github.com/user-attachments/assets/52e041bc-9f67-4ed2-9f85-240131f60c47)
If you want some sort of admin command however we can add that, just please make a feature suggestion for it on our discord server

**Comment by ThomasWega** [comment]
> * Changes I made in chat games also won't reload despite using the /achat reload command

Works completely okay for me. With changes on reload

**Comment by ThomasWega** [comment]
/p

> * When I click on the player message, the player name does not appear, it appears as /report %player_name%
>       (PlaceholderAPI Installed on My Server)

send me your configuration and I'll test

**Comment by frknmrl** [comment]
And I noticed one more thing about chatcolor, for example, when VIP members expire, the colors they chose with /chatcolor are not reset

**Comment by frknmrl** [comment]
> /p
> 
> > * When I click on the player message, the player name does not appear, it appears as /report %player_name%
> >   (PlaceholderAPI Installed on My Server)
> 
> send me your configuration and I'll test


[vip.txt](https://github.com/user-attachments/files/17558418/vip.txt)
[config.txt](https://github.com/user-attachments/files/17558421/config.txt)

**Comment by frknmrl** [comment]
> > * Changes I made in chat games also won't reload despite using the /achat reload command
> 
> Works completely okay for me. With changes on reload

Unfortunately it doesn't work for me, for example I have to turn the server off and on for changes in chat games. 

Additionally, I can say this for chat formats: The PlaceholderAPI plugin is installed on my server and works without any problems.

While the click event in the Prefix section in chat formats works correctly, the click events in the chat section do not work correctly.

**Comment by frknmrl** [comment]
https://github.com/user-attachments/assets/4e159aac-351b-48fe-8a5c-3687f9301a41

**Comment by ThomasWega** [comment]
Should be fixed in the next update. If any issue still is present, please create a new issue. It's getting pretty hard to spot anything in here :D
