### ISSUE TITLE
Command /msg and /r not working

### ISSUE THREAD

**Issue by MisterMakey** [AdvancedPlugins/Chat#212]
### Describe the bug

1.21.0 Velocity
We have a problem with /msg and /r. The tab completion isn't working either.

<img width="560" alt="Screenshot_500" src="https://github.com/user-attachments/assets/9530ffd7-e6ba-47a8-824c-2b3ecdb768a4">
<img width="552" alt="Screenshot_499" src="https://github.com/user-attachments/assets/967f9f59-0ee4-4e70-a353-95d54ec702a9">

### How to reproduce

/pm Works

**Comment by ThomasWega** [comment]
Show your log and potentially a video showcase please
