### ISSUE TITLE
Bugs with the %advancedchat_tag% placeholder

### ISSUE THREAD

**Issue by EvaliaCraft** [AdvancedPlugins/Chat#213]
### Describe the bug

Hello,
There's a problem with the %advancedchat_tag% placeholder. If you want to remove the space to stick the tag to the player's nickname, you can't, so it's a problem.
![image_2024-11-01_172937728](https://github.com/user-attachments/assets/43c6665d-8887-4174-89da-13a86db08c29)

### How to reproduce

for example, I'd like the heart to be next to the nickname, but that's not possible

**Comment by ThomasWega** [comment]
<img width="521" alt="image" src="https://github.com/user-attachments/assets/017dce75-4c01-460a-9a4b-c3cfd26253be">
in menus/chatTagsMenu.yml
