### ISSUE TITLE
Update to 1.5.9 No chat function anymore. (From 1.5.6)

### ISSUE THREAD

**Issue by MisterMakey** [AdvancedPlugins/Chat#214]
### Describe the bug

After the update, no one can type anymore. It doesn’t matter which server they’re on. You open the chat, type something, and nothing happens.

Before, we at least had everything duplicated; now there's nothing at all…

Velocity Network (Servers 1.21.0)

<img width="560" alt="Screenshot_507" src="https://github.com/user-attachments/assets/431712d2-b070-4d0e-b888-782b31e08e77">

### How to reproduce

All players without the * permission can’t type, even though they have the correct permissions.

**Comment by MisterMakey** [comment]
We're back to version 1.5.6: No chat anymore
Version 1.5.5: No chat

Simply nothing at all…

**Comment by ThomasWega** [comment]
That seems wild. Can you try deleting all the perms for AChat and deleting the AChat plugin folder please
