### ISSUE TITLE
 Player Head Skins Support in AdvancedChat

### ISSUE THREAD

**Issue by M0dsTERx** [AdvancedPlugins/Chat#216]
### Describe the bug

Hello!
I’m currently using[ EssentialsXChat](https://www.spigotmc.org/resources/essentialsx.9089/) with [ChatHeadFont](https://github.com/OGminso/ChatHeadFont) to display player heads next to chat messages. I would like to know if AdvancedChat supports a similar feature for showing player head skins in chat, or if it is possible to integrate this functionality directly. 

**Thank you!**

### How to reproduce

1.Install EssentialsXChat and configure the chat format to {skin } {player_name}> {message} or %skin%%player_name%> %message% to display player heads in chat.
2.Install ChatHeadFont with PAPI placeholders to show player skins.
3.Install AdvancedChat.
4.Try to replicate the player head skins feature with AdvancedChat.
5.Note that AdvancedChat does not have support for PAPI player head skins, unlike EssentialsXChat and ChatHeadFont.

### Screenshots / Videos

https://prnt.sc/sdbZ9Vf4Mlgp

**Comment by ThomasWega** [comment]
If it provides PAPI placeholders, you should be able to use that in all our messages and formattings just fine. If it doesn't, we'd need to add it. If that's the case, you can request this as a feature on our discord.



> 5.Note that AdvancedChat does not have support for PAPI player head skins, unlike EssentialsXChat and ChatHeadFont.

We have PAPI support. There might be a specific message where it's not parsed though. Feel free to send your config
