### ISSUE TITLE
Muting a player causes their chat to break

### ISSUE THREAD

**Issue by EmanYm** [AdvancedPlugins/Chat#217]
### Describe the bug

The target player's chat signature is revoked when they are muted.
There is nothing out of the ordinary posted in server or client consoles.

Now that I am looking, it appear as though we are at least two releases behind (1.5.9).  I will get the license holder to update the plugin and come back to report if it still happens in the latest version (1.6.2).

### How to reproduce

Mute player
they cannot send messages
unmute player
Chat tokens broken

### Screenshots / Videos

https://gyazo.com/a450c50f9eae4146e26cc099af793a5d
(*Edit: The url seemed to have been cut off and was not showing the image*)

**Comment by ThomasWega** [comment]
This might be a case of a plugin conflict. Possibly something with your proxy if you use any. Without further details about your server setup I cannot do anything

**Comment by EmanYm** [comment]
This was happening on my stand-alone dev server.

I did not have time at that moment to test with _just_ AdvancedChat, but I will in the morning.

**Comment by ThomasWega** [comment]
Any updates?

**Comment by EmanYm** [comment]
I apologize, I have ADOSS (Attention Deficit...OH!  SHINY STUFF!) and got distracted.
I will do this _right now_.

**Comment by EmanYm** [comment]
Alright, so I got my sister to log in on her computer this time, because I thought maybe me two-boxing was causing the invalid signature.  It still happened
[What I see on my screen](https://gyazo.com/83f6b473cbc1dd62cacb921d7626fdb2)
[What i see in console](https://gyazo.com/be1afd759048f40f1b3209de4054124a)
[What she sees on her screen](https://cdn.discordapp.com/attachments/515328613063852043/1309174801713070263/snip.png?ex=67409f8c&is=673f4e0c&hm=8af6d40ddb53df033cdd7c51ed0600b01a1f7ba01f32703b11be708044bcbdd2&)

Purpur 1.21.1
AdvancedChat 1.6.3
No proxy

**Comment by ThomasWega** [comment]
Try updating your paper. Seems like this issue was there even without any plugins
https://github.com/PaperMC/Paper/issues/11400

**Comment by EmanYm** [comment]
I use Purpur, so I doubt I will get that fixed until I can update to 1.21.3.
Thank you for your time anyway, Thomas.
