### ISSUE TITLE
Customize default command names/aliases

### ISSUE THREAD

**Issue by heykiditsaaron** [AdvancedPlugins/Chat#22]
### Describe the feature

It would be nice if AdvancedChat could hook into Towny Chats. I dont know anything about what it takes, but Ive seen _TownyChat AsyncChatHookEvent_ mentioned more than a few times.

**Comment by ThomasWega** [comment]
What would be the reason for this?

**Comment by heykiditsaaron** [comment]
I have a lack of understanding of how towny chat, or any of them honestly, works. But I also notice that it looks like advanced chat snatches up chat messages and converts them into server commands, probably tell raw or whatever. Anyway, towny chat allows you to chat  to members of towns/nations where it's only visible to members of said town/nation. But any time you use it, advanced chat grabs it and posts it globally to where every member of the server can see it.

**Comment by ThomasWega** [comment]
Next update there will be API Events which will allow you to cancel or change AdvancedChat messages handling. Anyone can hook into this and make these both plugins work however he wants. You'll probably need a developer though. 

I am thinking whether we could implement this ourselves though. If you are able to explain what exactly happens now and what you'd like it to do, and provide some example if possible. We might be able to implement this

**Comment by heykiditsaaron** [comment]
Honestly I'm not entirely sure how they do it. Probably not worth messing with if you have plans of introducing your own chat sections. However, a towny conflict I'm more concerned with is the /t command being used for some form of message sending by advancedchat. Maybe a way to disable certain commands/aliases?

**Comment by ThomasWega** [comment]
That could be a feature request. For sure something we'll work on. Thank you

**Comment by ThomasWega** [comment]
You have commands.yml file now for customization of everything for commands
