### ISSUE TITLE
Player death triggers the message: {nick} died.

### ISSUE THREAD

**Issue by mrWezyr** [AdvancedPlugins/Chat#220]
### Describe the bug

After a player dies, instead of a custom message or the original minecraft message about how the player died, the same message appears. I tried the default config and I have the same problem

### How to reproduce

Install AdvancedChat 1.6.3 on paper 1.21.1

### Screenshots / Videos

![mspaint_fSzO0CJs21](https://github.com/user-attachments/assets/72dc77b0-5acf-475e-bc49-96aa50a3074c)

**Comment by ThomasWega** [comment]
Try deleting your old deathMessages file. Also make sure you have default value in the config 
![image](https://github.com/user-attachments/assets/0e5e2000-fa2a-444c-97ad-3ba4ffa1427f)

**Comment by mrWezyr** [comment]
I deleted the old file, restarted the server, and the file reappeared with all default settings. The death message appeared correctly. I used /advancedchat reload, and everything was still fine. However, after restarting the server, the message {nick} died returned.

**Comment by ThomasWega** [comment]
Is it possible to get a video showcase please?

**Comment by mrWezyr** [comment]
I tested a little more. Restart doesn't matter, but the type of death does. I don't know what's going on anymore xd
Is it possible for me to enable some debugging function and send you its results?
Video: https://www.youtube.com/watch?v=LAuQPC4Gcas

![obraz](https://github.com/user-attachments/assets/43d45fb5-a02b-4784-a6ad-2f00f22bb1b4)

**Comment by ThomasWega** [comment]
On which type of death does this happen? I will try to reproduce it

**Comment by ThomasWega** [comment]
(nvm, you've sent a video)

**Comment by ThomasWega** [comment]
Wil be fixed in the next update
