### ISSUE TITLE
still errors with bedrock players names

### ISSUE THREAD

**Issue by RykerTheWolf49** [AdvancedPlugins/Chat#221]
### Describe the bug

I'm on the latest version of AdvancedChat v1.6.5 this issue was supposedly fixed in the latest updates but I'm still having issues with bedrock players when using any kind of usrn prefix with floodgate Advanced chat becomes very unhappy spamming the server console with errors 

### How to reproduce

simply setup geyser, floodgate and AdvancedChat run the server then join as a bedrock player and if you have any prefix for bedrock usernames you'll be greeted with a bunch of errors in the server console possibly even overloading the server

### Screenshots / Videos

![issue](https://github.com/user-attachments/assets/169be9d0-62c6-4074-83c0-84ef05a04044)

### Server Log

https://mcpaste.io/e9ac271920fb37df

**Comment by ThomasWega** [comment]
Improved it next update. Hopefully not will work fine
