### ISSUE TITLE
Join/Leave messages will not show in chat.

### ISSUE THREAD

**Issue by tantaf123** [AdvancedPlugins/Chat#222]
### Describe the bug

in my server, Any version of advanced chat above 1.5.8 will not show the join and leave messages every player normally sees when someone is joining or leaving a minecraft server. One of the support team members tried to help but unfortunately their method didn't work. So at the moment I'm having to make use of version 1.5.8

### How to reproduce

`

**Comment by ThomasWega** [comment]
you need to negate permission `advancedchat.ignorejoinformat.<format>` for everyone

**Comment by tantaf123** [comment]
what am i supposed to do, I'm stuck using advanced chat 1.5.8

anything above that just won't show the join message

**Comment by Telmarine** [comment]
I can confirm this. I'm running 1.11.5 and the vanilla join messages no longer fire in game or on console. This started today.
