### ISSUE TITLE
Compatibility with SuperiorSkyBlock2

### ISSUE THREAD

**Issue by miloshykk** [AdvancedPlugins/Chat#225]
### Describe the bug

Hi. When a player types /is chat to switch chat to island chat, the message is sent normally in general chat instead of island chat. /is chat is the option to switch chat so that any message sent sends to the island chat. /is chat <message> works fine, but you have to keep typing the alias in front of the message, which is cumbersome.

### How to reproduce

AdvancedChat version: 1.6.9
Just install AdvancedChat and SSB2, and use the /is chat command to change the chat type to island, and try to write something in the chat.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/0f4c8b85-ed98-4e5e-98fe-1c8e9b03ca4f) 
This is how the message should be sent, but it is only sent properly after using the /is chat (message) command.
![image](https://github.com/user-attachments/assets/24dd02f6-c2bb-4380-81cf-43a4f99e8f69)
This happens after typing /is chat itself, and sending another message that should be sent in island chat but is sent in general chat.

**Comment by ThomasWega** [comment]
Either chat should be handled only by the other plugin and in that case it should cancel the chat event before us or if you want us to add some kind of hook for compatibility between these plugins, you'd need to create a feature request on our github
