### ISSUE TITLE
Channel info not shown with ProtocolLib

### ISSUE THREAD

**Issue by 53ba5tian** [AdvancedPlugins/Chat#226]
### Describe the bug

Hey there,

I noticed that if I use the command /channel info the result is as it is shown in the screenshot.

As you can the there is no information about the channel. This accourse when I have ProtocolLib along AdvancedChat. I tested it without and everything works fine.

### How to reproduce

1. Paper Server (V. 1.21.1-127)
2. AdvancedChat 1.6.10 und ProtocolLib 5.3.0

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/fb339f82-1d45-40cf-9b1c-23f87a4d9e24)

**Comment by ThomasWega** [comment]
Was a deeper issue than just ProtocolLib, but it will be fixed in the next update. Thanks for reporting
