### ISSUE TITLE
Error fetching player skin AdvancedChat

### ISSUE THREAD

**Issue by hbojoe** [AdvancedPlugins/Chat#227]
### Describe the bug

When Geyser / Bedrock players join the server there's an error fetching player skin.

### How to reproduce

Server running Paper version 1.20.6-151-ver/1.20.6@a4f0f5c
Running Geyser-Spigot Build #728
Running Floodgate Build #728
AdvancedChat 1.6.9 or 1.6.10

Join server with Geyser / Bedrock and error is shown.

### Screenshots / Videos

![Opera Snapshot_2024-12-10_185017_gamer namehero com](https://github.com/user-attachments/assets/8e5804b3-148f-47bc-8bad-427decb6717a)

### Server Log

https://mcpaste.io/07e140313d640396

**Comment by ThomasWega** [comment]
We currently only support geyser player prefixes with `.` in front. You will need to change this or add a feature request on our discord to add config option for this
