### ISSUE TITLE
1.7.0 plugin version brutal crash! 

### ISSUE THREAD

**Issue by Kremo28** [AdvancedPlugins/Chat#228]
### Describe the bug

Everything is fine in theory I have Java 21 paper for 1.20 and the AC version is 1.7.0 when starting the server it gives 3 big errors for no reason and when the load progresses at least 6 or 7 more however the plugin works but every When you send a message or execute a command (anything), it sends a super error or sometimes several.

### How to reproduce

Only download 1.7.0 

### Screenshots / Videos

![Captura de pantalla (17)](https://github.com/user-attachments/assets/ee527abe-2759-4be6-8224-c11b4057e275)
![Captura de pantalla (18)](https://github.com/user-attachments/assets/34339e5d-21c4-4ce0-83c3-13fed037c7be)
![Captura de pantalla (19)](https://github.com/user-attachments/assets/e6ec9ef9-cc94-4656-a564-5611a8dcd196)
![Captura de pantalla (20)](https://github.com/user-attachments/assets/d650aa35-fb18-4298-9b08-39b7aad8a533)
![Captura de pantalla (21)](https://github.com/user-attachments/assets/5f2a094d-3d5d-4a54-adbe-1fe90501f43b)
![Captura de pantalla (22)](https://github.com/user-attachments/assets/f2131f27-67e4-4225-85c9-db7f569ca40e)
![Captura de pantalla (23)](https://github.com/user-attachments/assets/a6e536db-67d2-4d8e-b3b8-40208ea19370)
![image](https://github.com/user-attachments/assets/2ecaddac-d6a9-4e43-a0e2-fcebe28cb607)

### Server Log

https://mcpaste.io/ad51ab7004ebdf21

**Comment by GC-spigot** [comment]
Hi! Update your java version to Java 21 :) That will help you fix it.
