### ISSUE TITLE
broken intervals

### ISSUE THREAD

**Issue by Z3r0xh** [AdvancedPlugins/Chat#23]
### Describe the bug

The interval option within ads does not work, it continues to remain at 5 minutes even if it is modified

### How to reproduce

I have changed the interval option from 300 to 10 and it continues to remain at 300 even though the file is at 10s

**Comment by GC-spigot** [comment]
Hi! Did you try restarting? :)

**Comment by Z3r0xh** [comment]
> Hi! Did you try restarting? :)

Restarting seems to be yes, but couldn't you add modifying the interval in real time?

To see how they look or some way to see the ad you are making style
/ac announcer view one

**Comment by GC-spigot** [comment]
We'll fix reload command and definitely can add such feature :)

**Comment by Z3r0xh** [comment]
> We'll fix reload command and definitely can add such feature :)

Thanks you very much!!!

**Comment by GC-spigot** [comment]
Solved for next update
