### ISSUE TITLE
problem with legacy color support & minimessage implementation

### ISSUE THREAD

**Issue by Z3r0xh** [AdvancedPlugins/Chat#24]
### Describe the bug

I have a problem when implementing messages and legacy colors

![image](https://github.com/AdvancedPlugins/Chat/assets/138524212/9f1c582b-8e9f-4d3a-800f-5e1bb8e4bebe)

this is my format
https://pastebin.com/HcTH2brS

### How to reproduce

just add various hovers and click actions to the placeholders

**Comment by ThomasWega** [comment]
Were you able to figure out which part of the text this happens at?

**Comment by Z3r0xh** [comment]
What I can't get is that it looks good, it still appears like in the photo no matter how much I modify things

**Comment by ThomasWega** [comment]
if you remove the placeholder or use only minimessage it will work fine right?

**Comment by Z3r0xh** [comment]
> if you remove the placeholder or use only minimessage it will work fine?

I found the solution by trying things with the prefix, but yes, the plugin is doing something wrong when loading the minimum messages.

**Comment by ThomasWega** [comment]
it will be a combination of legacy and minimessage which causes this. Could you please assist us in figuring out the exact scenario in which this happens? What have you replaced to fix this? Can you give some examples when it does happen and when it does now please?

**Comment by Z3r0xh** [comment]
> it will be a combination of legacy and minimessage which causes this. Could you please assist us in figuring out the exact scenario in which this happens? What have you replaced to fix this? Can you give some examples when it does happen and when it does now please?

I will gladly help you.

I have realized that when using hex colors in the placeholder and putting it inside a hover with more options:

(<hover:show_text:'<white>---------------------------------------- --------</white>\n<color:#ff1c03> This is the owner of the server!</color> \n<white>-------------- ----------------------------------</white>'><click:open_url:'https:// store.unnamecraft.com/'>%vault_prefix%</click></hover><reset>)

This one was giving an error and it is taking out the colors of the placeholder as if it were minimessages, already, it is something strange to be honest.

While I was editing the achat format for a while, it occurred to me to change the placeholder of %vault_prefix%, to which I added an &r at the end and it stopped making errors.

So my conclusion is that there is something with minimesages that doesn't work...

this is my prefix now from vul_prefix:

prefix.10.&#000000&l[&#d60000&lO&#eb1a2a&lW&#ff3453&lN&#eb1a2a&lE&#d60000&lR&#000000&l]&r

With this it works, but if you remove the final &r it won't and it will show it to you as if it were minimesages.

**Comment by ThomasWega** [comment]
We'll investigate this. Thank you. Glad you were able to figure out a solution
