### ISSUE TITLE
bug with chat AI

### ISSUE THREAD

**Issue by Rcorcho6** [AdvancedPlugins/Chat#25]
### Describe the bug

The error appears when the AI ​​kicks when it detects a rudeness [edited repository file with server name] but when kicking the error came out

### How to reproduce

https://pastes.dev/WR1yE0pmf0

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/86140264/0dffe641-981d-4904-b16b-09b9fa5c4f57)

**Comment by GC-spigot** [comment]
solved!
