### ISSUE TITLE
Join/Leave messages stop working after being kicked

### ISSUE THREAD

**Issue by Schroddinger** [AdvancedPlugins/Chat#26]
## The error
When a player gets kicked out from the server (this happened because of connection issues) the joining and leaving messages stop triggering from that point onwards.

This is how the console looks.
![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/1b3200f2-4d12-4a4a-9a11-21e36b7dc32f)

This is how the ingame chat looks.
![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/396dfa29-5a9f-4e08-8652-3be2aa2613cd)

## Steps
* Join the game.
* Get kicked out from being unable to send keepalive packets.
* Try to join and leave again.

**Comment by ThomasWega** [comment]
My only guess is that bukkit doesn't send join and leave events for this player for some reason. We literally just listen to those

**Comment by Schroddinger** [comment]
Maybe one of my plugins is cancelling the event, I'll do some tests and let you know what I find.
But it's weird that only happens to AChat after a player is kicked out, other plugins that listen to the player joining and leaving are still working.

**Comment by ThomasWega** [comment]
I am confused as well. I don't even have a rough guess of why that might be happening right now. How did your tests go?

**Comment by Schroddinger** [comment]
Not great, every player gets their message when joining/leaving after being kicked. Somehow, since that day, L0very no longer sends join and leave message, even after restarting the server, I thought it might be a permission but they have the same rank and permissions as Biquaternions, so I'm not sure what's happening.

**Comment by ThomasWega** [comment]
sooo.. It works for one player but not the other one? If so then it's super strange

**Comment by Schroddinger** [comment]
Yup. I might not be able to keep testing for a while. I run seasonal servers and this one has reached its end, next one will be ready in roughly a year.
I'll be creating the next one with AChat, but in a dev environment. I'm not sure if I'll be able to replicate the issue there (plugins and therefore conditions will change),
I think it might be best to close this issue and wait if someone reports something similar.

**Comment by ThomasWega** [comment]
Agreed. Thank you for your input though. Glad to hear you'll continue using AChat
