### ISSUE TITLE
bug in tag and chatcolor permissions

### ISSUE THREAD

**Issue by Rcorcho6** [AdvancedPlugins/Chat#28]
### Describe the bug

All the necessary permissions are assigned to use /tags and /chatcolors and we select but in the chat it says you do not have permissions, even though we have all the permissions

### How to reproduce

when we try to select a chat tags and/or color

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/86140264/4875d8ae-b2b5-42c4-b732-2936a37a372a)

**Comment by ThomasWega** [comment]
Hey! What permissions are you trying out? What's your config? We need specific information, we cannot solve anything like this

**Comment by heykiditsaaron** [comment]
For context

**Comment by ThomasWega** [comment]
will close this as a duplicate of https://github.com/AdvancedPlugins/Chat/issues/27 and handle the issue there
