### ISSUE TITLE
/tags and /chatcolor do not work and player mentioning in chat doesnt work

### ISSUE THREAD

**Issue by Vasito1** [AdvancedPlugins/Chat#3]
### Describe the bug

/tags and /chatcolor give an error when used. @ing players also doesnt work it sometimes bolds the name but thats about it

### How to reproduce

Run the command and it gives the error.

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/118059072/da9060dd-0e0f-430b-a05e-69fcd3f2ee8e)
![image](https://github.com/AdvancedPlugins/Chat/assets/118059072/cc848662-6726-43b4-aeaf-a0e0a73b5379)

**Comment by Vasito1** [comment]
Also chat filtering works really well when its all 1 word but can we bypassed using spaces 
![image](https://github.com/AdvancedPlugins/Chat/assets/118059072/28a11659-8d3c-4fe0-85c7-d6b815ab6daf)

**Comment by GC-spigot** [comment]
Hey, first issue is already fixed on 1.0.2 :) We'll fix the spaces bypass very soon.

**Comment by Vasito1** [comment]
Hey! @GC-spigot really nice also I recommend making the mention similar to this plugin
https://www.spigotmc.org/resources/chatpings.76261/

**Comment by Vasito1** [comment]
Also for links in chat like /discord you should make it so that the link is clickable

**Comment by Vasito1** [comment]
Also can you make the autoannoucements use the same format as the commands like this:
- "MESSAGE: "
      - "MESSAGE: §x§3§A§6§5§F§2&lJ§x§3§A§6§5§F§2&lo§x§3§A§6§5§F§2&li§x§3§A§6§5§F§2&ln §x§3§A§6§4§F§2&lT§x§3§A§6§4§F§2&la§x§3§A§6§4§F§2&lv§x§3§A§6§4§F§2&le§x§3§A§6§4§F§2&lr§x§3§A§6§4§F§2&ln§x§3§A§6§3§F§2&lM§x§3§A§6§3§F§2&lC §x§3§A§6§3§F§2&lD§x§3§A§6§3§F§1&li§x§3§A§6§3§F§1&ls§x§3§A§6§3§F§1&lc§x§3§A§6§2§F§1&lo§x§3§A§6§2§F§1&lr§x§3§A§6§2§F§1&ld §x§3§A§6§2§F§1&lS§x§3§A§6§2§F§1&le§x§3§A§6§2§F§1&lr§x§3§A§6§1§F§1&lv§x§3§A§6§1§F§1&le§x§3§A§6§1§F§1&lr§x§3§A§6§1§F§1&l!"
      - "MESSAGE: &7Stay up to date with all §x§5§8§6§5§F§2announcements&7,"
      - "MESSAGE: §x§5§8§6§5§F§2giveaways&7, §x§5§8§6§5§F§2events&7 and much more!"
      - "MESSAGE: "
      - "MESSAGE: §x§5§8§6§5§F§2&ndiscord.gg/tavernsmp"
      - "MESSAGE: "

**Comment by ThomasWega** [comment]
> Also can you make the autoannoucements use the same format as the commands like this:
> 
>     * "MESSAGE: "
>       - "MESSAGE: §x§3§A§6§5§F§2&lJ§x§3§A§6§5§F§2&lo§x§3§A§6§5§F§2&li§x§3§A§6§5§F§2&ln §x§3§A§6§4§F§2&lT§x§3§A§6§4§F§2&la§x§3§A§6§4§F§2&lv§x§3§A§6§4§F§2&le§x§3§A§6§4§F§2&lr§x§3§A§6§4§F§2&ln§x§3§A§6§3§F§2&lM§x§3§A§6§3§F§2&lC §x§3§A§6§3§F§2&lD§x§3§A§6§3§F§1&li§x§3§A§6§3§F§1&ls§x§3§A§6§3§F§1&lc§x§3§A§6§2§F§1&lo§x§3§A§6§2§F§1&lr§x§3§A§6§2§F§1&ld §x§3§A§6§2§F§1&lS§x§3§A§6§2§F§1&le§x§3§A§6§2§F§1&lr§x§3§A§6§1§F§1&lv§x§3§A§6§1§F§1&le§x§3§A§6§1§F§1&lr§x§3§A§6§1§F§1&l!"
>       - "MESSAGE: &7Stay up to date with all §x§5§8§6§5§F§2announcements&7,"
>       - "MESSAGE: §x§5§8§6§5§F§2giveaways&7, §x§5§8§6§5§F§2events&7 and much more!"
>       - "MESSAGE: "
>       - "MESSAGE: §x§5§8§6§5§F§2&ndiscord.gg/tavernsmp"
>       - "MESSAGE: "

Test it out on latest
