### ISSUE TITLE
holywhitescroll | AChat and AEnchantments

### ISSUE THREAD

**Issue by 0Kilz** [AdvancedPlugins/Chat#30]
### bug holywhitescroll | achat and aenchantments

When you put a holywhitescroll to an item, and you die the lore of the weapon should disappear but when you use the AChat and AEnchantments plugin this lore does not disappear and does not let you put a holywhitescroll even though the weapon no longer has it, I'll attach a video if I did not explain well

I am sure that this error only happens when I add AChat, I have made tests to remove AChat and the error disappeared but when adding it the error happened again in all the objects that added a holywhitescroll.

Currently I have only tested it with the holywhitescroll I am not sure if this happens with the whitescroll or the enchants.

Right now I have tested the plugins with the latest versions of both and the error remains, AChat 1.0.6 AEnchantments 9.7.17

### How to reproduce

1. Add holywhitescroll to any item
2. Die with this item
3. The item no longer has the holywhitescroll effect but still appears in the item's description as if it did.
4. Try to add holywhitescroll to it (it doesn't let you add holywhitescroll to it because it already has it in the description but the effect doesn't exist anymore)
5. Die again with this item and the item will drop even though it says it has holywhitescroll in the description.

### Screenshots / Videos

https://youtu.be/d4GLPEUpw68

**Comment by ThomasWega** [comment]
Hey! Can you test again with both on latest please?

**Comment by 0Kilz** [comment]
the error is already solved with the latest versions of both plugins, thank you very much.
