### ISSUE TITLE
Chatcolor Enhancement

### ISSUE THREAD

**Issue by CptToastey** [AdvancedPlugins/Chat#31]
### Describe the feature

- Add ability to disable chat color command /chatcolor 
- Allow for colors to be applied to a player with a command
- Allow for description of colors
- Allow for GUI to self adjust on pages needed
- Allow option to only show what player has unlocked or allow player to see all but show a different icon if the color is locked

Thanks for considering :)

**Comment by Sp00kableDev** [comment]
+1

**Comment by whosLevity** [comment]
Please for the love of god, let us disable chat color formatting, or atleast make the chatlistenerpriority actually work.

**Comment by ThomasWega** [comment]
Hey! Great suggestion! We have moved suggestions to discord, where community votes on features to be added. Not a lot of people use github. If you are still interested in us adding this feature, please add it in the discord server. Thank you! <3
