### ISSUE TITLE
Issue with PlaceholderAPI

### ISSUE THREAD

**Issue by Xqow** [AdvancedPlugins/Chat#32]
### Describe the bug

When ever I use any placeholder api placeholder in this case for vault suffixes supplied by luckperms and the placeholder value is not set / the player doesn't have a suffix it sends a very long error in chat and it puts <none> for the suffix. It looks like it's listing of every possible permission or luckperms entry on the server

### How to reproduce

I changed the suffix placeholder in the defaults.yml layout to %vault_suffix% and %luckperms_suffix%, both worked when a suffix was set and both sent the error in the screenshot attached.

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/131767001/2929f08c-c06b-41db-a3ee-b47e469b9152)
![image](https://github.com/AdvancedPlugins/Chat/assets/131767001/9097db44-d093-4df7-8459-8a35ac4c7581)

**Comment by ThomasWega** [comment]
Hey! Please send the full error, not just parts. A video showcase would help as well. Thanks!

**Comment by Xqow** [comment]
I managed to fix it
