### ISSUE TITLE
You can parse placeholders by simply typing them

### ISSUE THREAD

**Issue by ArabianPandaMC** [AdvancedPlugins/Chat#33]
### Describe the bug

Players are able to parse placeholders in chat/pms.

### How to reproduce

By simply writing a placeholder in chat, it will parse it for you, this creates a major security issue as sensitive placeholders may be used, sending a user a private message will also parse the placeholder for them.

**Comment by Schroddinger** [comment]
I can confirm this is indeed an issue.
Critical placeholders like `%player_ip%` are **sometimes** blocked by anti-advertisement.

![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/1bed17f5-d9b7-41e7-9888-2faf0164e634)

Server RAM can be displayed.

![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/38cf59ae-9dec-4f6a-9961-facd31d4369d)

This was tested on Minecraft 1.20.4 inside a channel. I'm not currently aware if this will work outside of a channel.

**Comment by ThomasWega** [comment]
Will be fixed in the next update! Thanks for reporting and sorry for the delay.
