### ISSUE TITLE
Enhanced Chat Color Configuration

### ISSUE THREAD

**Issue by whosLevity** [AdvancedPlugins/Chat#34]
### Describe the feature

I have two requests, one of which I saw has already been mentioned. 

1. The ability to disable achat's chat colors.
2. This plays into 1, I have a custom plugin that handles chat colors already as well as a variety of other cosmetic features. AChat blocks this from working. I believe being able to disable chat colors would make this work, since nothing is hooking into the game's chat colors.

**Comment by whosLevity** [comment]
![image](https://github.com/AdvancedPlugins/Chat/assets/20944689/04a62c2c-d4bd-4e17-9ec2-171055a1df09)


This is the issue I'm running into on the latest version. My suggestion was literally just the messages.

**Comment by ThomasWega** [comment]
Duplicate of https://github.com/AdvancedPlugins/Chat/issues/31
