### ISSUE TITLE
DiscordSRV Support

### ISSUE THREAD

**Issue by Xqow** [AdvancedPlugins/Chat#36]
### Describe the bug

I am not fully sure if this is a bug or just an issue on my end, but it seems like that AdvancedChat fully breaks the minecraft -> discord chat bridge supplied by discordsrv. In the discord channel it no longer sends any chat messages from the minecraft server.

### How to reproduce

Install DiscordSRV on a server, set it up, type a message on the server: It should show up, but does not.

**Comment by ThomasWega** [comment]
duplicate of https://github.com/AdvancedPlugins/Chat/issues/18
