### ISSUE TITLE
Bug when trying type in chat on 1.19 Minecraft server 

### ISSUE THREAD

**Issue by Sizzle08** [AdvancedPlugins/Chat#37]
### Describe the bug

What happens is whenever I type something in chat on my 1.19 Minecraft server a list of permissions is typed above my chat in green every single time I type something and this is without me configuring anything at all. 

### How to reproduce

Just load onto a 1.19 server and try to type it won’t work without putting a list of those permissions above it’s really weird.

### Screenshots / Videos

![help](https://github.com/AdvancedPlugins/Chat/assets/140993362/b00daedd-dc01-49cc-b015-d885b9659a2f)

**Comment by GC-spigot** [comment]
Hi! Ill check this out and let you know in a day or two, having a minor surgery today and won't be online until a day after.

**Comment by Sizzle08** [comment]
> Hi! Ill check this out and let you know in a day or two, having a minor surgery today and won't be online until a day after.

Sounds good let me know once fixed plugin looks really cool want it to be functional on my server.
