### ISSUE TITLE
Operators getting wrong prefixes 

### ISSUE THREAD

**Issue by Sizzle08** [AdvancedPlugins/Chat#38]
### Describe the bug

So basically whenever I give someone operator on my server even though they are ranked as one prefix there rank in just chat changes to the owner prefix instead of the one they had before they were operator and when I unop them it goes back to the prefix they had to begin with.

### How to reproduce

Give someone operator and it gives them the highest role in the format file that you have set up.  No matter what there actually ranked in the server.

**Comment by Sizzle08** [comment]
> That is as expected, as operator you have all permissions.
> 
> What you need to do is give the OP a negative permission e.g. -permission.here this way you remove that permission from the player.

I gave the OP a permission level of 2 and it's still not working. I am not sure how I am suppose to give the OP negative permission I dont know what you mean by that

**Comment by ThomasWega** [comment]
When you set a permission, by default the permission sets it's value to true. You can however set the value of permission to false as well, which will negate it. Luckperms example:
/lp user USER permission set PERM false
