### ISSUE TITLE
[item] with chatcolors

### ISSUE THREAD

**Issue by Kapakulia** [AdvancedPlugins/Chat#39]
### Describe the bug

When you do [item] it shows the items and the end show colors ending example </dark_red>

### How to reproduce

Select chat color and do [item]

### Screenshots / Videos

![image_2024-05-02_121518129](https://github.com/AdvancedPlugins/Chat/assets/25252776/145464ad-29de-47ac-a2ed-01774604449a)

**Comment by Kapakulia** [comment]
Hey, here is for that sameone in screenshot, but the default colors have same issue.
`    radioactive:
      format: "<gradient:#D4FF00:#25BE23>%message%</gradient>"
      name: "<gradient:#D4FF00:#25BE23>RadioActive</gradient>"
      material: SLIME_BALL`

**Comment by ThomasWega** [comment]
Will be fixed in the next update
