### ISSUE TITLE
Make formatting modular/support legacy color codes

### ISSUE THREAD

**Issue by whosLevity** [AdvancedPlugins/Chat#4]
I have a custom cosmetic plugin that directly changes player messages for example. The two plugins do not work together, allowing us to toggle that on and off would fix that.

In addition, my cosmetics also uses legacy color codes, which seems to break the plugin. In my scenario, players can earn nickname tickets and create their own name, that portion works fine, but when a nickname color (gradient) is applied to the nickname, it doesn't support the colors properly.

**Comment by whosLevity** [comment]
[06:18:39 ERROR]: Could not pass event AsyncPlayerChatEvent to AdvancedChat v1.0.3
net.advancedplugins.chat.impl.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
         §8§l»§r 
         ^^

**Comment by ThomasWega** [comment]
> [06:18:39 ERROR]: Could not pass event AsyncPlayerChatEvent to AdvancedChat v1.0.3 net.advancedplugins.chat.impl.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information. §8§l»§r ^^

This will be fixed in the next update!

**Comment by whosLevity** [comment]
Using the kyorify expansion this was fixed. Main thing now for me is the ability to use something like that for the internal %message% placeholder

**Comment by whosLevity** [comment]
Just updated to 1.0.4, it now completely ignores my custom chat message formatting. Ideally this would become modular so I can still use it.

**Comment by ThomasWega** [comment]
Can you give an example of what broke?

**Comment by whosLevity** [comment]
I have a cosmetic plugin that does titles, nicknames, hats, tab colors, chat colors, etc. AdvancedChat overrides the chat color the people select on my end. I still want to use default chat colors, set up in config for staff, but I also want my plugin (dev is mia) to take priority when setting a chat color.

**Comment by whosLevity** [comment]
Is this something that is possible?

**Comment by ThomasWega** [comment]
Hey! If you want a compatibility with some other plugin, please create a new issue where you specify what you need us to provide and fix. I will mark this as solved now
