### ISSUE TITLE
Advanced Chat

### ISSUE THREAD

**Issue by Ya0bi** [AdvancedPlugins/Chat#42]
### Describe the bug

I get this big error in the console, the plugin works fine but i can't /advancedchat reload which is pretty annoying

### How to reproduce

i deleted those: 
![image_2024-05-04_190244727](https://github.com/AdvancedPlugins/Chat/assets/161828502/f20e4e97-bc11-414a-9429-1cbd44812561)

### Screenshots / Videos

[message.txt](https://github.com/AdvancedPlugins/Chat/files/15210427/message.txt)
Thats the error i get in the console

**Comment by Ya0bi** [comment]
i deleted everything that was after line 19

**Comment by ThomasWega** [comment]
It's because you've deleted the channels section. Either put it back and leave it empty or wait for the next update where we handle this correctly
