### ISSUE TITLE
A place to put a tag if you want the tag as prefix.

### ISSUE THREAD

**Issue by Ricozaur** [AdvancedPlugins/Chat#44]
### Describe the feature

You can add it as a prefix via "prefix" behind the actual prefix, but when you do and you have no tag there will be a space before everything which doesn't look nice in chat. I've been looking and i can't find a feature like this, excuse me if there is.
![Capture](https://github.com/AdvancedPlugins/Chat/assets/41333341/a5d1c17a-5f1f-4328-80dc-4aac7e62a045)
![Capture2](https://github.com/AdvancedPlugins/Chat/assets/41333341/0be3c0f4-7bcc-4182-a1c7-9ab49a573f65)

**Comment by Ricozaur** [comment]
This also happens when you enable a tag, it add a unneccesary space before it

**Comment by ThomasWega** [comment]
The space before can be turned off in chatTagsMenu.yml `addSpaceBeforeTag: false`. Next update `addSpaceAfterTag` will be added as well
