### ISSUE TITLE
Attempting to use formatting on commands file with the discord.yml

### ISSUE THREAD

**Issue by Thefluffypvper1** [AdvancedPlugins/Chat#47]
### Describe the bug

When attempting to use the hover feature in-game, it seems that the functionality isn't working as expected. Instead of displaying the hover text when someone hovers over the hyperlink, the entire message including the hover tag is shown in the chat. This suggests that there might be an issue with how the hover tag is being interpreted or processed by the game's system.

https://gyazo.com/9e0cc94bd105c6d301dfb089784439db

### How to reproduce

# These commands are fully customisable, you can delete them, create new ones

# Argument variables
# - %arg-N-N% (example %arg-1-4%)
# - %arg-N-END% (example %arg-2-END%)
# - %command% (base command name)
# - %label% (command used supporting aliases)

# You can disable commands by changing the file extension.
# For example change "time.yml" to "time.yml.off"

baseCommand: /discord
description: Link to server's discord!

# Put unlimited conditions and effects
command:
  - effects:
      - "MESSAGE:&fJoin <insert:test>this</insert> our discord server at&e https://discord.gg/yourdiscordinvite <hover:show_text:'<red>Hover with a<newline><green>line break'>Text with<newline>line break</hover>"
      
      use the same config for discord.yml and use /discord

**Comment by ThomasWega** [comment]
Send the config formatted in code blocks please. This is unreadable. https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by Thefluffypvper1** [comment]
> Send the config formatted in code blocks please. This is unreadable. https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

https://paste.helpch.at/ebasuliqub.makefile

**Comment by ThomasWega** [comment]
If effects, minimessage formatting doesn't work yet. You cannot use click and hover events. Only legacy colors and hex. https://ae.advancedplugins.net/plugin-information/faq#hex-colors. And maybe gradients, not sure
