### ISSUE TITLE
Private messages incorrect order

### ISSUE THREAD

**Issue by Thefluffypvper1** [AdvancedPlugins/Chat#50]
### Describe the bug

When attempting to message people its meant to show the receivers name first not the senders name, this will confuse players thinking they are sending messages to them selfs.

### How to reproduce

Privet message a alt account on the same server

### Screenshots / Videos

[When attempting to message people its meant to show the recievers name
https://gyazo.com/02da2e8c288cd26fe9d9bf12c6bd2e48

**Comment by ThomasWega** [comment]
You can change that formatting in lang file
