### ISSUE TITLE
Cancel event not working for players messaging offline players

### ISSUE THREAD

**Issue by Thefluffypvper1** [AdvancedPlugins/Chat#51]
### Describe the bug

When messaging offline players its ment to cancel the message and say something on the line of "player isn't online"

### How to reproduce

privet message any person who is offline

**Comment by ThomasWega** [comment]
Works fine? 
![image](https://github.com/AdvancedPlugins/Chat/assets/82312488/ad2e1f22-d970-493d-8bb7-7778b5b22706)
Does it also autocomplete the offline player for you?

**Comment by Thefluffypvper1** [comment]
Once my director is online i will ask him to update to newest version to see if i have the same issue

**Comment by Thefluffypvper1** [comment]
The newer update fixed this issue, thank you
