### ISSUE TITLE
Hex colors not working with placeholderapi 

### ISSUE THREAD

**Issue by Thefluffypvper1** [AdvancedPlugins/Chat#52]
### Describe the bug

When I use other 3rd party placeholders like  %luckperms_prefix% it doesn't show the hex color because this plugin requires <> to be around the hex color

### How to reproduce

Create a luckperms rank with a hex color then proceed to use the %luckperms_prefix% placeholder into Chatmotd in lang.yml and you will see that hex color doesn't work

### Screenshots / Videos

https://gyazo.com/d40535902a876d55d7356f5a9b2b9e26

**Comment by ThomasWega** [comment]
What exactly is returned by %luckperms_prefix% please? I don't see any & at the start. We support legacy

**Comment by Thefluffypvper1** [comment]
https://gyazo.com/5d34a77c588461ed5a7ba2ef8da4804c

**Comment by ThomasWega** [comment]
yeah there's no & at the start of the hex. If you insert it there, it should work
