### ISSUE TITLE
Out of sync tag spam

### ISSUE THREAD

**Issue by Thefluffypvper1** [AdvancedPlugins/Chat#54]
### Describe the bug

When you repeatedly press the "Next" button and then try to select a tag, it doesn't work because the rapid navigation might cause the tag selection mechanism to get out of sync. Here's a breakdown of the possible reasons for this issue:

Event Handling Overload: Spamming the "Next" button might trigger too many events in a short period, causing the event handlers for the tag selection to fail or not execute properly.

State Management Issues: The application might not be managing its state correctly, leading to inconsistencies. For example, the tag selection component might not be aware of the most recent state due to the rapid changes caused by spamming the "Next" button.

Debouncing or Throttling Missing: Without debouncing or throttling, the system tries to process every single "Next" button click, overwhelming the application's ability to handle subsequent actions like tag selection.

UI Rendering Delays: The UI might not have enough time to render the new state before the next action occurs, causing elements to become unresponsive or not clickable.

### How to reproduce

Open /Tags spam the next button, then attempt to select tag

### Screenshots / Videos

https://gyazo.com/8b41f575aedf7cf1631112c97dcbb399

**Comment by ThomasWega** [comment]
Will be fixed in the next update
