### ISSUE TITLE
Hex color doesn't work on /tags icons

### ISSUE THREAD

**Issue by Thefluffypvper1** [AdvancedPlugins/Chat#55]
### Describe the bug

Issue: The hex color codes for tag icons in the GUI are not rendering correctly. Instead of displaying the specified color, the tag icons show a different color than intended, as demonstrated in the provided screenshots. This discrepancy is evident when compared to the correct color display in the chat.

Example:

GUI Color: Example https://gyazo.com/637bc7be2fb3ca5c7ed6d59c127feacf
Chat Color: Example https://gyazo.com/623d0f9e508abc6389486aabb8a1d4b5
Request: Please investigate the color rendering logic for GUI tag icons to ensure hex colors are applied consistently.

    bow:
      format: "&8[<#8B4513>🏹&8]"
      material: BOW
      
      Use this config for any tag

### How to reproduce

    bow:
      format: "&8[<#8B4513>🏹&8]"
      material: BOW
      
      Use this config for any tag

### Screenshots / Videos

https://gyazo.com/637bc7be2fb3ca5c7ed6d59c127feacf
https://gyazo.com/623d0f9e508abc6389486aabb8a1d4b5

**Comment by GC-spigot** [comment]
It's likely a configuration issue, show your message that lets them know tag is set. It may be using 2 colors at a time in one place.

**Comment by Thefluffypvper1** [comment]
> It's likely a configuration issue, show your message that lets them know tag is set. It may be using 2 colors at a time in one place.

bow:
  format: "&8[<#8B4513>🏹&8]"
  material: BOW
  
  Use this config for any tag
  

This was my config for the tag

**Comment by Thefluffypvper1** [comment]
You can come on my faction server and come see it message me on discord if you want Doocho#4520

**Comment by ThomasWega** [comment]
Hey! Have you made sure that all your other configurations have enclosed tags? Example:
```<red> needs to be enclosed with </red> before using new color```

**Comment by ThomasWega** [comment]
It's misconfiguration for sure though
