### ISSUE TITLE
Cap sensitive for emoji use

### ISSUE THREAD

**Issue by Thefluffypvper1** [AdvancedPlugins/Chat#56]
### Describe the bug

We need to ensure that users can use emojis in chat without case sensitivity. This means that regardless of whether the emoji input is in uppercase, lowercase, or a mix of both, it should be recognized and rendered correctly.

Example:
Users should be able to type emojis in any case, such as :smile:, :SMILE:, or :SmIlE:, and have them display correctly in chat.

### How to reproduce

use any emoji from the file and attempt to use the same format just change one of the letters to cap and you will see it doesn't work

**Comment by GC-spigot** [comment]
This is fine how it currently operates, I see no reason to support those. It's not possible by our internal systems either.
