### ISSUE TITLE
Cant Assign Format Rank to Players & Players Cant Use /tags or /colors

### ISSUE THREAD

**Issue by Hoviax** [AdvancedPlugins/Chat#57]
### Describe the bug

The permissions dont seem to be applying. Its not working when players try to use the /tags and /colors command in chat. I also cant assign the Format Rank to players. Its not working on a command level. 

### How to reproduce

error message on /colors and /tags. As op it doesnt let me assign a format rank from the console or in game chat.

**Comment by GC-spigot** [comment]
Hi, 


If there is an error - show the error. For formats, you need to apply negative permissions for formats you do not want player to have.

**Comment by Hoviax** [comment]
Here are the error messages below and a screenshot of the default permissions already set. Can you give me an example of the negative permissions and where i set that at?

Thank you for your help btw, I really appreciate it.

![advancedchat default permissions](https://github.com/AdvancedPlugins/Chat/assets/170225276/e31b8a5d-6be3-419a-a8fe-f8312441a9dc)
![Screenshot 2024-05-19 134730](https://github.com/AdvancedPlugins/Chat/assets/170225276/67512a64-9bd6-4cd9-8bb0-71a55b110bfc)
![Screenshot 2024-05-19 134730](https://github.com/AdvancedPlugins/Chat/assets/170225276/01c2d091-0ae8-4239-b88d-bfa4017f7f00)

**Comment by ThomasWega** [comment]
That depends on what plugin you use for perms. But LuckPerms example would be 
/lp user USER permission set PERM false

**Comment by ThomasWega** [comment]
Btw. You don't have permissions set for the menus. Check here: https://chat.advancedplugins.net/main/commands-and-permissions

**Comment by Hoviax** [comment]
Hi Thomas, all of the permissions are applied **except** for ignoring player perms. I use a GUI for permissions and went through every one and applied them all including the **.use** & **.colors** permissions as shown in the screenshot. I even created a unique permission for **advancedchat.command.chatcolor** , **advancedchat.command.tags** , **advancedchat.command.tags.list** , & **advancedchat.command.tags.apply** since it wasn't list and still nothing. It's giving the exact same error message as shown above. 

The format also didn't work the way your wrote it. Not sure if its because im using a GUI for perms or not. Is there not a way to set the format through the plugin file for individual players?

**Comment by Hoviax** [comment]
Hi, still waiting for an update on this.

**Comment by ThomasWega** [comment]
The permissions are

advancedchat.command.tags
advancedchat.command.chatcolor

The GUI won't show you all permissions. It's better to go with the wiki https://chat.advancedplugins.net/main/commands-and-permissions

**Comment by Hoviax** [comment]
Hello, I literally wrote in my previous reply that **exact** command and I said I manually applied it and it’s STILL not working. Please read my last message thoroughly. Is someone going to actually help me or not?On May 27, 2024, at 5:21 PM, ThomasWega ***@***.***> wrote:﻿
The permissions are
advancedchat.command.tags
advancedchat.command.chatcolor
The GUI won't show you all permissions. It's better to go with the wiki https://chat.advancedplugins.net/main/commands-and-permissions
