### ISSUE TITLE
customizer.yml not working correctly

### ISSUE THREAD

**Issue by Thefluffypvper1** [AdvancedPlugins/Chat#59]
### Describe the bug

When testing out the default setting on customizer.yml it doesn't appear to be working

unknownCommand:
  findType: EQUALS # This means `fromMessage` must be exactly the same as the message to replace
  find: '&fUnknown command. Type "/help" for help.'
  replace:
    0: # You can replace multiple parts of the message, this way keeping original message's variables, e.g. special variables. PlaceholderAPI is still supported here!
      from: '&fUnknown command. Type "/help" for help.'
      to: '&cYou''ve typed an unknown command! Type "/help" for help or use "/discord" to join our Discord server!'

### How to reproduce

Use default setting and make Unknown command. Type "/help" for help. in chat  and you will see "&cYou''ve typed an unknown command! Type "/help" for help or use "/discord" to join our Discord server!" is ment to appear but it doesn't

**Comment by GC-spigot** [comment]
Do you have ProtocolLib installed?

**Comment by Thefluffypvper1** [comment]
I had a outdated sorry about that
