### ISSUE TITLE
MSG/TELL command not working nor autocompleting

### ISSUE THREAD

**Issue by Schroddinger** [AdvancedPlugins/Chat#6]
### Describe the bug

When using `/msg` it should suggest/autocomplete the first parameter with the player names. **This does not happen**
If you try to write username manually and send a message it will always return `This player is not online!` regardless if the player is online and not in vanish.

### How to reproduce

Try writing `/msg` or `/tell` and sending a message.
If this does not happen to you, please let me know to record a video or show the server setup.

### Screenshots / Videos

Autocomplete is not working

![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/ff7b83f9-5f74-4175-ac25-9e34c927dcea)

This happened using an alt account, trying to message my main account.
The `.` is intended. It also happens with the test account that has no `.`.

![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/ea07d957-1f7c-43c3-9623-e3a3cbd9ff17)

The permissions are properly assigned (The message wasn't that the player had no permission anyways).

![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/4dbd4116-5f22-4304-b9ea-49b2f8999ba1)

**Hope this helps!**

**Comment by GC-spigot** [comment]
Fixed!
