### ISSUE TITLE
Hex color and lore for customizer.yml not working

### ISSUE THREAD

**Issue by Thefluffypvper1** [AdvancedPlugins/Chat#61]
### Describe the bug

When attempting to add multiple lores and use  hex colors  it doesn't work 

### How to reproduce

you can use my config if you want
https://pastes.dev/dBdIusrq0D

basicly use any hex color in the process and for the lore part use the bottom part of the config in any example

### Screenshots / Videos

you can use my config if you want
https://pastes.dev/dBdIusrq0D

basicly use any hex color in the process and for the lore part use the bottom part of the config in any example

https://gyazo.com/4105790d6a5a021a3ca72fff8ecb4ae3

**Comment by ThomasWega** [comment]
I've already told you once in a different issue that you don't use the hex colors correctly. You are missing the & char
