### ISSUE TITLE
MINI-MESSAGE STILL DOESNT WORK EVEN THO YALL SAID IT WILL BE FIXED

### ISSUE THREAD

**Issue by FlattestDisc108** [AdvancedPlugins/Chat#63]
### Describe the bug

_sigh..._ https://github.com/AdvancedPlugins/Chat/issues/45

### How to reproduce

https://github.com/AdvancedPlugins/Chat/issues/45

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/168830838/1fd74d0a-79a1-41cf-81f9-a3d38fc58759)

**Comment by ThomasWega** [comment]
The update has not been pushed yet. It will soon
