### ISSUE TITLE
Relational Placeholders

### ISSUE THREAD

**Issue by Willi4mDev** [AdvancedPlugins/Chat#67]
### Describe the feature

It would be great if it were possible to synchronize everything that can be synchronized on the plugin, such as chat, to be able to create "global" channels which are shared between all the servers, therefore also doing it with chatgames.

Please keep support for relational placeholders in a sync case.

**Comment by ThomasWega** [comment]
Which relational placeholders would you like to see?

**Comment by Willi4mDev** [comment]
Basically relations colors for factions

**Comment by ThomasWega** [comment]
Otherwise except chat games, everything is able to be synchronized now
