### ISSUE TITLE
Channel switching does not work

### ISSUE THREAD

**Issue by QuartzWarrior** [AdvancedPlugins/Chat#69]
### Describe the bug

Using the /channel join command does not work, not even with the right permissions

(This has been tested on Purpur 1.20.2 - Build 2095)

### How to reproduce

Create a channel
Assign your user the appropriate permissions for it
Have them use the /channel join command
The command will not go through, and the user will just get the "No permission" message

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/74436633/ae03c0da-486c-4bbb-a1bd-25d999d92e9f)
![image](https://github.com/AdvancedPlugins/Chat/assets/74436633/47b2c4f6-e10f-4592-a137-46994defcaf7)

**Comment by ThomasWega** [comment]
Indeed. Will be fixed in the next update!
