### ISSUE TITLE
Placeholder showing the player reading the message instead of the one actually joining/leaving

### ISSUE THREAD

**Issue by Schroddinger** [AdvancedPlugins/Chat#7]
### Describe the bug

When a player joins/leaves the server, the message is broadcasted as expected.
What is not expected is that users see their own usernames instead of the one joining/leaving.

The plugin I was using before had its own placeholder `{player}`, maybe it was to prevent this.

### How to reproduce

1. Use the placeholder `%player_name%` provided in the default config.
2. Join the server with two accounts.
3. Join and leave with one of them.
4. Watch the result in the second account.

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/7df5d9cd-be53-478b-bb2c-9f0d947caf30)

**Comment by GC-spigot** [comment]
Fixed! Thanks for reporting

**Comment by Schroddinger** [comment]
Hi, I'm testing the patch and it now only happens when the player leaves the server.
Is there a new placeholder for that?

![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/5ecd35d4-3f67-411d-82b8-a176301ccbd8)
