### ISSUE TITLE
Multiple channel prefixes

### ISSUE THREAD

**Issue by QuartzWarrior** [AdvancedPlugins/Chat#71]
### Describe the feature

Hello, could there be an option to have the name of a channel and the chat prefix not be the same (e.g: upon joining the "Global" channel you would get the message: "You have joined the Global channel," but when you would type a message, it would show up as "[G]" instead of "[Global]")? Thank you in advance!

![image](https://github.com/AdvancedPlugins/Chat/assets/74436633/a683e5f3-a5ed-423f-a1b1-bf5c55b1aad4)
![image](https://github.com/AdvancedPlugins/Chat/assets/74436633/0740d228-2df7-4d64-8a65-ca1f0cac98de)

**Comment by ThomasWega** [comment]
There is already a placeholder %channel_id%, which he could use. That would show the name of the config section. Or you can possibly also use %advancedchat_channel%, but not 100% sure that will be parsed. Both will show this value

![image](https://github.com/AdvancedPlugins/Chat/assets/82312488/5ea75366-c191-4ebe-a861-3cf883a9ef1b)

**Comment by ThomasWega** [comment]
I guess we could also add something like multiple prefixes, but not sure if that's necessary

**Comment by QuartzWarrior** [comment]
> There is already a placeholder %channel_id%, which he could use. That would show the name of the config section. Or you can possibly also use %advancedchat_channel%, but not 100% sure that will be parsed. Both will show this value
> 
> ![image](https://private-user-images.githubusercontent.com/82312488/334097960-5ea75366-c191-4ebe-a861-3cf883a9ef1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMTgxMzQsIm5iZiI6MTcxNzAxNzgzNCwicGF0aCI6Ii84MjMxMjQ4OC8zMzQwOTc5NjAtNWVhNzUzNjYtYzE5MS00ZWJlLWE4NjEtM2NmODgzYTllZjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDIxMjM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYWM0ZjQ1ODVjMTgyMjk1N2M1NTc4OGIyNjNhZWJkNWMxMWJlMmM5NzBmNjFlYWNlYTRmMTVmNzE0MWJmNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5d00EhhCiQ4BtQLKVx1RjlRHGfl-AXa9BjXepgB2liU)

In my opinion, having people type /channel join L or having them see that they joined the L channel would just lead to confusion.

**Comment by ThomasWega** [comment]
Will be added in the next update
