### ISSUE TITLE
Hex codes aren't applied in the ChatColor GUI items Titles

### ISSUE THREAD

**Issue by RedxAx** [AdvancedPlugins/Chat#72]
### Describe the bug

Hex codes aren't applied in the ChatColor GUI items Titles, it will reconfig to the closest legacy  color

### How to reproduce

use any hex code.

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/144875043/92f6dde5-f09e-4ddd-ada8-db30250492e5)
![image](https://github.com/AdvancedPlugins/Chat/assets/144875043/e0e3d4be-6a20-493b-8680-04f1215381c0)

**Comment by ThomasWega** [comment]
What color formatting do you use?

**Comment by ThomasWega** [comment]
<img width="660" alt="image" src="https://github.com/AdvancedPlugins/Chat/assets/82312488/a8fdab43-536a-4789-9a66-9a88771628a3">

**Comment by ThomasWega** [comment]
Works completely fine. I do recommend closing the colors tag though
