### ISSUE TITLE
Incompatibility with InteractiveChat

### ISSUE THREAD

**Issue by iCodeYT** [AdvancedPlugins/Chat#74]
### Describe the bug

![image](https://github.com/AdvancedPlugins/Chat/assets/62040329/74ffe091-524d-4329-821a-5664b70e69c3)

### How to reproduce

This happens anytime I use [item]

**Comment by ThomasWega** [comment]
Update to latest and regen your advertising.yml rule

**Comment by iCodeYT** [comment]
Im using the latest update, 1.1.6, i regen the file, still same issue, it only works if i disable the advertising.yml completely.

**Comment by ThomasWega** [comment]
Can you send the file contents here?

**Comment by iCodeYT** [comment]
enabled: true

# ends with %allow% to allow the effects to be executed, not the message.
# %message_stripped% removes color codes (included invalid ones) and replaces them with an empty string. If this is not done, the regex might not work as expected.
conditions:
  - '%message_stripped% matchesregex \b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b || %message_stripped% matchesregex \b(?:[a-zA-Z0-9-]{1,63}\.)+[a-zA-Z]{2,6}\b : %allow%'

# REPLACE_MESSAGE:<from>:<to> to replace the message with <to> if it contains <from>
# MESSAGE:<message> to send a message to the player
# CANCEL_EVENT to stop message from going through
effects:
  - 'CANCEL_EVENT'
  - 'MESSAGE:&c&l(!) &c%player name%, advertising is not allowed on the server.'
  # - 'CONSOLE_COMMAND:warn %player name% advertising' # you could also warn the player here

**Comment by ThomasWega** [comment]
hmm. I am not able to replicate this for some reason

**Comment by iCodeYT** [comment]
Just to avoid confusion, Im talking about the [item] from InterativeChat, not AdvancedChat's Built in item variable.
Tested it on another server, same issue

**Comment by ThomasWega** [comment]
ohhh. That makes sense then

**Comment by ThomasWega** [comment]
Why use two plugins then? Just disable our variable and use the InteractiveChats one. Or the other way around

**Comment by iCodeYT** [comment]
That's what I do, I deleted the variable, but it still does this.

**Comment by ThomasWega** [comment]
If you can get the author of InteractiveChat here, that'd be great. I am honestly unsure how to approach this to keep compatibility

**Comment by ThomasWega** [comment]
Actually.. updating to latest will fix this
