### ISSUE TITLE
DiscordSRV incomparable + Work around

### ISSUE THREAD

**Issue by AngelicMonk** [AdvancedPlugins/Chat#76]
### Describe the bug

As stated in the discord, AdvancedChats shut down one of our favorite plugins which handles chat between in game and discord chat, allowing users to chat between the two, called DiscordSRV. 

I've noticed if we put a MC chat color in front of our messages, it "breaks" advanced chat and allows discord SRV to work for that message. 

Example message "&7 Hello Discord" will remove all formats, prefixes, suffixes etc and allow the message to go through.

### How to reproduce

Type "&7 (message)" when you have discord SRV and AdvancedChat installed and setup.

### Server Log

https://mcpaste.io/84aff11de493fa49

**Comment by GC-spigot** [comment]
Solved, discordsrv support added
