### ISSUE TITLE
"Legacy formatting codes have been detected"

### ISSUE THREAD

**Issue by natecarra** [AdvancedPlugins/Chat#77]
### Describe the bug

I've been using the same format on 1.1.5 and added some gradients to messages before upgrading to 1.1.6. On the upgrade, it said all of my formats are "Legacy formatting code". Tried upgrading today to 1.1.7 to see if it would solve my issue however I am continuing to get the same messages. There's no error messages in game when I type in chat and I used to not even be able to say any messages in chat, now it looks like some print.

### How to reproduce

Leaving my config for default.yml from the format config to hopefully help reproduce.

# This is a default format, so it will be applied to everyone by default.
# WE RECOMMEND KEEPING THIS DEFAULT FORMAT (feel free to change anything except the file name).
priority: 1
prefix:
  text: '%prisonranksx_currentrank_displayname% <gradient:#b8b8b8:#616161>[Member] '
  hover:
    - '<gray>%player_name%<white> Information:</white>'
    - '<gray> •<white> Balance: <white>%vault_eco_balance%</white>'
    - '<gray> •<white> Health: <white>%player_health%/%player_max_health% �?�</white></white>'
    - '<gray> •<white> Level: <white>%player_level%</white></white>'
  # https://jd.advntr.dev/api/4.14.0/net/kyori/adventure/text/event/ClickEvent.Action.html
  click: 'SUGGEST_COMMAND:/msg %player_name% '
name:
  text: "<gradient:#b8b8b8:#616161>%player_name%"
  hover:
    - '<gray>%player_name%<white> Information:</white>'
    - '<gray> •<white> Balance: <white>%vault_eco_balance%</white>'
    - '<gray> •<white> Health: <white>%player_health%/%player_max_health% �?�</white></white>'
    - '<gray> •<white> Level: <white>%player_level%</white></white>'
  click: 'SUGGEST_COMMAND:/msg %player_name% '
suffix:
  text: '%advancedchat_tag%: '
  hover:
    - ''
  click: ''
chat:
  text: '<gray>%message%'
  hover:
    - '<red>Report %player_name%'
  click: 'SUGGEST_COMMAND:/report %player_name%'
# Customisable range. If set to 0, range will be disabled.
# Channel range overrides this range and takes a higher priority.
range: 0.0

### Screenshots / Videos

[https://mcpaste.io/ad906da59044717f](https://mcpaste.io/ad906da59044717f) (Starts at Line 436)
![image](https://github.com/AdvancedPlugins/Chat/assets/171198841/12a22c96-667b-4ea7-8320-fe861e390bf5)

### Server Log

https://mcpaste.io/ad906da59044717f

**Comment by natecarra** [comment]
Update: Attempted to update to the newest version of the plugin; however, I am still getting basically the same errors.
https://mcpaste.io/959d4626d3ef3d11
Same config file as above

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Apologies, incorrect git merge messed this up
