### ISSUE TITLE
Hover doesnt work on 1.20.6

### ISSUE THREAD

**Issue by itsDanny5555** [AdvancedPlugins/Chat#78]
### Describe the bug

If you hover with your Cursor over the Name or a Format Group, nothing appears.
No Errors or warns in console.

### How to reproduce

Download the latest 1.20.6 PaperMC and run protocollib, papi and AdvancedChat with luckperms.
On 1.20.4 works everything fine. (same setup)

### Screenshots / Videos

![Screenshot_2024-05-31_204911](https://github.com/AdvancedPlugins/Chat/assets/171385750/287e2c4b-7101-41d1-a7ab-2b882a2aac95)

**Comment by iCodeYT** [comment]
Same issue here, happens when hovering over names and messages for me. Happens to me even on 1.20.4

**Comment by ThomasWega** [comment]
Will be fixed in the next update
