### ISSUE TITLE
Autocomplete @Mention

### ISSUE THREAD

**Issue by Schroddinger** [AdvancedPlugins/Chat#8]
## Autocomplete
I don't know if it's a bug because the wiki says nothing about it, so I think is not a feature yet.
It would be great to autocomplete with the online players when typing the `@`.

The default Minecraft autocomplete also doesn't work with the `@`.
Trying to use it requires leaving an space after the `@`, autocompleting and then return the cursor to delete said space.

**Comment by ThomasWega** [comment]
The autocomplete is a feature request, however mentioning a player without char has been fixed and will work next update!

**Comment by ThomasWega** [comment]
I would love to do this, if it was as simple as it sounds. This would actually need to create fake player with these names, which would then need to be hidden from all the players, so they don't show in tablist. I am unsure if this won't break compatibility with other plugins, so I'd rather avoid it. If you can, just use plugin TAB
