### ISSUE TITLE
Minimessage Nicknames Don't Show.

### ISSUE THREAD

**Issue by DontMessWithDis** [AdvancedPlugins/Chat#80]
### Describe the bug

When I use a plugin called hexnicks for a gradient nickname and add the placeholder to the format folder under a role it doesn't parse the placeholder and sends me an error. I've tried making adjustments for various different placeholders within the plugin, but it appears to be because of the nickname format.
[message (1).txt](https://github.com/user-attachments/files/15519238/message.1.txt)

### How to reproduce

Download hexnicks, install with placeholderAPI and advanced chat, add the %hexnicks_nick% placeholder in place of the player's name for display in the format folder for the proper role. It likely will not show up when you reload the plugin to update the changes. It also might throw the error message I added above.

It will completely not send any messages as well so the placeholder will cause chat to stop working when a player sends a message.

### Screenshots / Videos

[message (1).txt](https://github.com/user-attachments/files/15519246/message.1.txt)

### Server Log

https://mcpaste.io/3ad9715f48d3bf42

**Comment by DontMessWithDis** [comment]
Anyone seen this?

**Comment by ThomasWega** [comment]
Update to latest
