### ISSUE TITLE
Error When Reloading After Making Any Change

### ISSUE THREAD

**Issue by DeOpping** [AdvancedPlugins/Chat#81]
### Describe the bug

Whenever I make any change to any file and then reload via `/advancedchat reload` it produces an error.

### How to reproduce

To reproduce, I think just make any change in any config file and then reload with `/advancedchat reload`
For example, for [this stacktrace](https://pastes.dev/50wMf9MUt5) all I did was add "Test" to the `name.text` string in formats/default.yml and reloaded via the command.

### Versions:
- Paper 1.20.6-129-master@0513374
- AdvancedChat 1.1.8
- ProtocolLib 5.2.1-SNAPSHOT-689

### Server Log

https://mcpaste.io/29f206792fb6888d

**Comment by GC-spigot** [comment]
Solved for next update, thanks!
