### ISSUE TITLE
Backslash ("\") at End Of Line Replaced By "<reset>"

### ISSUE THREAD

**Issue by mrericwong** [AdvancedPlugins/Chat#82]
### Describe the bug

**Bug Description**
Sending "\\" as the last character of the message will cause some troubles:
- If you send "\\", it will be sent as "\<reset>".
- If you send "\\\\", it will be sent as "\\".
- If you send "\\\<message>", it behaves as expected, sending as "\\\<message>".

**Server Information**
Version: Paper 1.20.6-124-master@0fcf3e3
Plugins (all enabled properly): AdvancedChat, Essentials, LuckPerms, ProtocolLib, Vault
AdvancedChat: v1.1.8 (Using the default configurations)
ProtocolLib: v5.2.1-SNAPSHOT-689
Vault: v1.7.3-b131

### How to reproduce

Send "\\" as the last character of the message.

### Screenshots / Videos

<img width="833" alt="Screenshot 2024-06-01 at 23 17 38" src="https://github.com/AdvancedPlugins/Chat/assets/125999837/d83a2dae-d48a-471d-a1fe-69fe3504ed0a">

### Server Log

https://mcpaste.io/637f796a7ba13c79

**Comment by ThomasWega** [comment]
Should be fixed in the next version. Thanks for reporting
