### ISSUE TITLE
"/ac reload" breaks the announcer until server restart.

### ISSUE THREAD

**Issue by Vehzx** [AdvancedPlugins/Chat#84]
### Describe the bug

When using /ac reload, the announcer stops announcing, even if all changes made in the announcements.yml have no errors or issues. Once doing a server restart and joining the game, the announcer works fine as usual, see in video below.

This isn't a huge issue, only when making the announcements as to see a change I made, I have to restart the server everytime.

### How to reproduce

put the automatic announcer on, wait until it announces something, then /ac reload

after it stops announcing, restart server, join to see it announces again.

### Screenshots / Videos

https://www.youtube.com/watch?v=KwXanprWYp8

### Server Log

https://mcpaste.io/a546aa0f9c142675

**Comment by ThomasWega** [comment]
Will be fixed on the next update. Thank you for reporting
