### ISSUE TITLE
Bypass AI filter for specific person or Ranks.

### ISSUE THREAD

**Issue by Mateusus7** [AdvancedPlugins/Chat#85]
### Describe the feature

So i was in the Discord asking this in the support, they said to post it in github, is the first time i do this.

So the feature would be to "disable"/whitelist AI Chat and Chat filters for specific ranks or users on the server like:

_whitelistRanks:_
  _- Owner_
  _- Admin_
  _- Staff_

Something like that,

**Comment by Link-c0p** [comment]
yes pleaseeeee

**Comment by Sp00kableDev** [comment]
+1

**Comment by ThomasWega** [comment]
Will be added in the next update
