### ISSUE TITLE
format placeholder issue

### ISSUE THREAD

**Issue by Thefluffypvper1** [AdvancedPlugins/Chat#86]
### Describe the bug

When configuring the chat formatting in the AdvancedChat plugin, certain placeholders cause the chat to stop working. The placeholders in question are %factionsuuid_faction_relation_color%, %factionsuuid_player_role%, and %factionsuuid_faction_name%.

### How to reproduce

Add the following configuration to the prefix section in the format file:
yaml
Copy code
text: '%factionsuuid_faction_relation_color%%factionsuuid_player_role%%factionsuuid_faction_name% &8▍ <#ff3030>&lOwner'
Save the changes and reload the plugin.
Observe that the chat stops working.

### Screenshots / Videos

https://paste.helpch.at/tivolumose.yaml

**Comment by ThomasWega** [comment]
Try latest update 1.2.0 please
