### ISSUE TITLE
Nametags Disabling Menus Folder

### ISSUE THREAD

**Issue by DontMessWithDis** [AdvancedPlugins/Chat#89]
### Describe the bug

Currently when I try to make a tag and change the format, when I restart the server it disables all of the menus. Also the gradients look completely different in chat than in the menu. Which is odd haha

### How to reproduce

Change from first format to second format and save and restart.
<gradient:#FF0000:#FF7F00:#FFFF00:#00FF00:#0000FF:#4B0082:#9400D3>[Queeeen]</gradient>
<gradient:#FF0000:#9400D3>[Queeeen]</gradient>

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/121703064/19f22e85-6a45-46b2-8dd4-2739f721fd52)
![image](https://github.com/AdvancedPlugins/Chat/assets/121703064/789218b6-2d80-4cd1-925c-f45045d6cd8c)

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Thanks for reporting!
