### ISSUE TITLE
User-friendly message for malformed colored messages

### ISSUE THREAD

**Issue by Schroddinger** [AdvancedPlugins/Chat#9]
## Current behavior
When sending a malformed colored message string it returns this.
In this case, the mistake is in `<\#005500>`.
I'm using `\` before the label at the end.

![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/a137a5e0-ea9f-4026-bbfd-429f8dbe65f1)

## Improvement
Instead of that huge red message, it would be best to just return a message informing the string is malformed, or ignore it completely unless is more critical.
I feel simplifying the message is enough although showing where the malformation is would be better (I feel that might not be necessary).

### This is good enough
![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/95adb61a-e2c8-40ba-887b-cd3f37c76916)

### This is not necessary, but is better
![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/708660e7-095c-4463-8b8c-4b4b92e0cfce)

**Comment by ThomasWega** [comment]
This will be fixed in the next update. It's because of the advertising rule, so we ignore special characters completely, so this won't be matched. Thanks for the report!
