### ISSUE TITLE
Advanced Chat Blocks Msgs From Outside Plugins

### ISSUE THREAD

**Issue by DontMessWithDis** [AdvancedPlugins/Chat#90]
### Describe the bug

I have a plugin called Welcome rewards and when a new player joins players type /welcome and it sends a message through the player to welcome the new player. The message from the player has stopped sending in chat.

### How to reproduce

Download welcome plugin
https://www.spigotmc.org/resources/welcome.44244/
Install and attempt to welcome a new player with /welcome

The plugin worked perfectly before I added AC

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/121703064/3b9faa96-ad47-4259-b889-ee6e4ba40197)
^^ What it looks like with AC disabled

**Comment by ThomasWega** [comment]
The other plugin should be calling a chat event, which it doesn't probably. Or he can even run our own event, which would be even better. This is most likely a request to the other author, not us
