### ISSUE TITLE
[AdvancedChat] Task #20 for AdvancedChat v1.2.0 generated an exception java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null

### ISSUE THREAD

**Issue by ququshkaaeng** [AdvancedPlugins/Chat#91]
### Describe the bug

When logging in to the server, an error is written in the console

### How to reproduce

When logging in to the server I get this error in the console -  https://mclo.gs/f06USM6

### Server Log

https://mcpaste.io/763bf5e65e968b20

**Comment by ThomasWega** [comment]
I need your chat channels config
