### ISSUE TITLE
HEX Support in chat

### ISSUE THREAD

**Issue by VISION6969** [AdvancedPlugins/Chat#93]
### Describe the feature

Requesting HEX support for chat rather than MiniMessage. 
Hex such as &#141414 , {#145141} https://i.imgur.com/z52onwH.png
Having these solves issues for various things such as luckperms prefix.

**Comment by VISION6969** [comment]
This may work but this doesnt 
{#eueye} as can be seen here in the image https://i.imgur.com/z52onwH.png
It works in luckperms

**Comment by ThomasWega** [comment]
Yes. We already support three different color formats. Legacy, legacy hex and minimessage. Just pick one. If I remember correctly LuckPerms also supports minimessage. And for sure legacy. It's already enough of a mess now, so unless necessary I want to prevent adding another formatting

**Comment by VISION6969** [comment]
I understand not adding additional formats. However this is primarily used by CMI. Henceforth all the ranks and items are made with this hex in my server. It's really a trouble to change them all to the other format. I have more than 60+ luckperms rank all in this format. Changing them all is very much of an issue.

**Comment by ThomasWega** [comment]
I understand that, but it will cause even more trouble with us adding this format, believe me. Conflicts could arise very easily.

**Comment by VISION6969** [comment]
https://i.imgur.com/Z7gCsQM.png 
Just tested out multiple formats none seem to work other than minimessage
#612616 doesnt work
&#52616 doesnt work 
{#515151} doesnt work 
<#151515> doesnt work 
and multiple more formats 
these formats are supported by almost all plugins . Minimessage is fairly not used anymore by the most popular plugins hex is a must. Let me know if  i did something wrong

**Comment by VISION6969** [comment]
https://i.imgur.com/L9iF3g9.png 
Minimessage doesnt work as well
<gradient:#084CFB:#ADF3FD>newbie</gradient>

**Comment by ThomasWega** [comment]
Aha. true. Will be fixed in the next update

**Comment by VISION6969** [comment]
I see, the update's already out. Is there possiblity of what i requested above to add? Since its nearly impossible to change all my Tags to the other hex format.i am talking about {#92836}
