### ISSUE TITLE
ClickEvent 'OPEN_URL' doesn't work / v1.2.0

### ISSUE THREAD

**Issue by pzc735** [AdvancedPlugins/Chat#95]
### Describe the bug

Hello. I tried to follow the link here via click, but there was no response. I tried to make it prompt me to follow a link when I click on the prefix, but it doesn’t work. File format/default.yml. Server version 1.20.1

### How to reproduce

1. go to format/*.yml
2. settings prefix -> click
3. Set text 'OPEN_URL:https://google.com'

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/172287991/5d375866-e1fe-4998-8d02-0a8809cc3dba)

**Comment by ThomasWega** [comment]
try setting it like so:

```yaml
click: "OPEN_URL:'https://google.com/'"
```

**Comment by pzc735** [comment]
doesn't work.
