### ISSUE TITLE
Console getting spammed with errors with newest update

### ISSUE THREAD

**Issue by DontMessWithDis** [AdvancedPlugins/Chat#97]
### Describe the bug

It’s just erroring out and spamming my console.
![IMG_5152](https://github.com/AdvancedPlugins/Chat/assets/121703064/4e29ab67-0f4e-410d-8997-faf05418ec5a)

### How to reproduce

Install the most recent version on a paper 1.20.4 server. 

### Screenshots / Videos

![IMG_5152](https://github.com/AdvancedPlugins/Chat/assets/121703064/51416e9b-f425-48b7-bbcc-bf75578b2655)
![IMG_5151](https://github.com/AdvancedPlugins/Chat/assets/121703064/d88c62ca-4de4-4ec2-af19-bc9e1019ea2a)

**Comment by ThomasWega** [comment]
Hmm. Somehow I am not able to reproduce this

**Comment by GC-spigot** [comment]
Should be solved, if it comes up again in next update reply to this message.
