### ISSUE TITLE
Using minecraft color codes in results in a "ArrayIndexOutOfBoundsExceptionIndex" java exception

### ISSUE THREAD

**Issue by Sp00kableDev** [AdvancedPlugins/Chat#98]
### Describe the bug

When you use purely the minecraft colorcode with nothing else it displays an error. 
Example: &n | &r

### How to reproduce

Version: v1.2.1
To reproduce:
Type: &n OR &r and send the message. 

Result:
[11.06 21:28:01] [Server] [ERROR] Could not pass event AsyncPlayerChatEvent to AdvancedChat v1.2.1
[11.06 21:28:01] [Server] java.lang.ArrayIndexOutOfBoundsExceptionIndex 1 out of bounds for length 1

### Screenshots / Videos

![2024-06-11_17 33 24](https://github.com/AdvancedPlugins/Chat/assets/62859356/6ba3b26e-48b3-4404-a41f-20a29d9cf567)
![error](https://github.com/AdvancedPlugins/Chat/assets/62859356/24f21fc7-0e7e-4e53-b3e8-53766a79cc22)

### Server Log

https://mcpaste.io/166de0caf84ea215

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
